### ISSUE TITLE
ResourceWarning: unclosed file <_io.BufferedReader... in static_file()

### ISSUE THREAD

**Issue by alecxe** [bottlepy/bottle#1000]
We've recently got this error coming from `static_file()` function ([this line](https://github.com/bottlepy/bottle/blob/master/bottle.py#L2910)):

> /usr/lib/python3.5/unittest/case.py:600: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/20170926_084744_545761.pdf'>
  testMethod()

`with` should fix it as it did in a similar issue: https://github.com/bottlepy/bottle/pull/611. Thanks.

**Comment by defnull** [comment]
Fixed for range-requests in 245386e. If the warning also appears in other situations, please open a new issue. Thanks :)
