### ISSUE TITLE
Feature Request: Monitor time span of wsgi calls

### ISSUE THREAD

**Issue by KoenigRigips** [bottlepy/bottle#1002]
Hey

There is a type of attack on webservers called regular expression DOS:
https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

It uses the fact, that re engines may take a lot of time for processing certain regular expression/string combinations. Using these with bottle e.g. by specifying /\<name:re:(x+x+)+y\> as URL pattern and requesting /xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx from the server result in the server getting stuck.

Do you think it might be useful to create an option, where the wsgi() call of Bottle objects is implemented as a new process started and the time used by this process is monitored? Do you see huge drawbacks in e.g. overhead?

I tried to do such an implementation just for the regular expression module. I created a class, which objects have the same interface like the re module, but calls like re.match() are embedded in the runtime checks. In bottle.py, you create one of these objects  and call it re instead of importing re.

Wrapping just the regular expressions into some time monitoring has less side effects than wrapping the complete wsgi() call. But on the other hand, I had a huge problem with passing the return values of the re functions from the created process to the calling one. Objects transferred using multiprocessing.Pipe() need to be pickable. The objects returned by re.match() are not pickable, I had to write a class, which has the same interface like the match objects, but which is pickable. So the code became ugly.

I had to use processes instead of threads, because you can kill processes in a clean manner. Threads have no terminate() method.
I tried to do such an implementation just for the regular expression module. I created a class, which objects have the same interface like the re module, but calls like re.match() are embedded in the runtime checks. In bottle.py, you create one of these objects and call it re instead of importing re.

Wrapping just the regular expressions into some time monitoring has less side effects than wrapping the complete wsgi() call. But on the other hand, I had a huge problem with passing the return values of the re functions from the created process to the calling one. Objects transferred using multiprocessing.Pipe() need to be pickable. The objects returned by re.match() are not pickable, I had to write a class, which has the same interface like the match objects, but which is pickable. So the code became ugly.

I had to use processes instead of threads, because you can kill processes in a clean fashion. Threads have no terminate() method.

I appended this wrapper class, the pickable match class and a small test script.[TimeGuardExample.zip](https://github.com/bottlepy/bottle/files/1385458/TimeGuardExample.zip)

Do you thing the wrapping of whole Bottle.wsgi() is a good idea?

**Comment by defnull** [comment]
> Do you think it might be useful to create an option, where the wsgi() call of Bottle objects is implemented as a new process started and the time used by this process is monitored? Do you see huge drawbacks in e.g. overhead?

Sure. Creating a new process per request is an enormous overhead, and it does not solve the problem. Even if you could monitor and detect malicious requests and kill the process, the harm is already done and blacklisting IPs does not help at all against a serious attack. The best you can do is to detect and filter malicious requests _before_ they reach the application server. The second best thing is to have enough redundancy and just kill unresponsive server instances (uWSGI already does this). Or to not have vulnerable regular expressions in request routes in the first place, of cause.

Any non-trivial web application is easy to ddos. Sending requests is cheaper for the attacker than computing the result for the server, especially if a database is involved. You don't need vulnerable route expressions for that.

**Comment by KoenigRigips** [comment]
Hmm yes you are right. Especially that the attack already happened when it is detected that way. Thank you.
