### ISSUE TITLE
Can not read Chinese Filename correctly when updating files.

### ISSUE THREAD

**Issue by andytt** [bottlepy/bottle#1030]
I can not get the filename with Chinese characters correctly in my Post Decorator `@app.post('/<filepath:path>')`.

I use `request.files.get('file')` to retrieve the files.

My HTML file writes：

```
<form action="" method="post" enctype="multipart/form-data">
      Upload file: 
      <br />
      <input type="file" name="file"/>
      <br />
      <input type="submit" value="Sent">
</form>
```

And I can see the entire filename such as `文件.pdf` in my Chrome Developer Tools.But when I use `bottle.request.files.get('file')`, I get the file extensions like `.pdf`. It seems that bottle does not support UTF-8 when updating files.

**Comment by defnull** [comment]
You are probably using http://bottlepy.org/docs/dev/api.html#bottle.FileUpload.filename which intentionally strips most non-ASCII characters to ensure the filename is safe and portable across a wide range of operating and file systems. You can get whatever the client sent to you via `FileUpload.raw_filename` but be careful. You MUST validate and sanitize these strings, as they are easy to fake by an attacker and may contain harmful characters.
