### ISSUE TITLE
Passing data to modal form bootstrap

### ISSUE THREAD

**Issue by Xenonheat** [bottlepy/bottle#1036]
I have been attempting to pass data passed to the html template from bottle app that contains pony orm elements and I cannot get it to load the data from the id that I have passed. Can I get some help?

Below is the posted HTML and JQuery
(Button to open modal form)
<div class="row">
				<div class="ingredient_list">
					<table>
						<thead>
							<tr class="tab_header">
								<th class="border-black left_important"> Ingredient </th>
								<th class="border-black"> Quantity </th>
								<th class="border-black" style="width: 15%;"> Edit </th>
								<th class="border-black"> Remove </th>
							</tr>
						</thead>
						<tbody>
							% for ingredient, custing in zip(ingredients, inventory):
								<tr>
									<td>{{ingredient.IngredientName}}</th>
									<td class="border-black">{{custing.Quantity}}</th>
									
									**<td><button class="landing_button" data-toggle="modal" data-target="#edit_ingredient_modal" data-ingredient="{{custing.CustIngID}}"><i class="fas fa-pencil-alt" style="color: black;"></i> </button></td>** (Primary Culprit)
									<td><button class="landing_button" data-toggle="modal" data-target="#remove_ingredient_modal"><i class="fa fa-minus-circle" style="color: black;"></i> </button></td>
								</tr>
							% end
						</tbody>
					</table>
				</div>
			</div>

(Modal Form)
<div class="modal fade" id="edit_ingredient_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content" style="background-color: #dcb235">
					<div class="modal-header">
						<h5 class="modal-title white" id="exampleModalLongTitle">Edit Ingredient</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<div class="container-fluid">
							<div class="row align-items-center">
								<p class="modal_text"> Change quantity of ... </p>
							</div>
							<div class="row align-items-center">
								<p class="modal_text"> Quantity:</p> <input type="number" class="quan_input" id="quantity_input">
								
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<form method="post" action="remove_ingredient">
							<button type="button" class="modal_button">Submit Changes</button>
					    </form>
     				</div>
				</div>
			</div>
		</div>

(JQuery)
$('#edit_ingredient_modal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var ingredient = button.data('ingredient') // Extract info from data-* attributes
  // var ingredient_name = 
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal_text').text('Change quantity of ' + ingredient)
  modal.find('.modal-text input').val(ingredient)
})

Thanks

**Comment by defnull** [comment]
This is not bottle-related. Please ask a javascript, jquery or bootstrap community for help.
