### ISSUE TITLE
Bottle redirect function seems to hang

### ISSUE THREAD

**Issue by Xenonheat** [bottlepy/bottle#1046]
When I do a redirect to a new page, Bottle will load the template associated with the route but will not call the function causing me to have to reload the page an extra time to complete changes made.
How do I fix this? (Note - It happens every other time I redirect).

Code
`@bottle.post('/edit_ingredient')
@pony.orm.db_session
def edit_ingredient():
    # Get Herby Session
    herby_session = bottle.request.environ.get('beaker.session')

    # Set Reloaded value to False
    herby_session['Reloaded'] = False

    # Variable that will hold ingredient id
    ingredientid = bottle.request.json['ingID']
    custing_record = CustomerIngredient[ingredientid]

    # Variable that will hold quantity inputted from user
    quantity_input = bottle.request.json['quan']
    custing_record.Quantity = quantity_input
    pony.orm.commit()  

    # Redirect the user back to landing page
    bottle.redirect("/inventory", code=303)` 

When it doesn't work I get this result:
`127.0.0.1 - - [03/Mar/2018 13:49:45] "POST /edit_ingredient HTTP/1.1" 303 0
127.0.0.1 - - [03/Mar/2018 13:49:45] "GET /popper.js.map HTTP/1.1" 404 2703`

When it does work I get this:
`127.0.0.1 - - [03/Mar/2018 13:51:15] "POST /edit_ingredient HTTP/1.1" 303 0
127.0.0.1 - - [03/Mar/2018 13:51:15] "GET /inventory? HTTP/1.1" 303 0
127.0.0.1 - - [03/Mar/2018 13:51:16] "GET /popper.js.map HTTP/1.1" 404 2703`

It just doesn't give me the redirect to the function associated with the url

**Comment by defnull** [comment]
> When I do a redirect to a new page, Bottle will load the template associated with the route...

I do not see any template decorator in your example and according to your logs the response is a zero-sized `303` which is exactly what it should be for a redirect.

**Comment by Xenonheat** [comment]
The template decorator for this issue is the following:
`@bottle.route('/inventory')
@user_required
def open_inventory():
    """ Serve ingredient inventory page """
    # Get Herby Session
    herby_session = bottle.request.environ.get('beaker.session')

    # Re-update Herby Session
    get_inventory()

    # Set parameters for variables
    inventory = herby_session['Inventory']
    ingredients = herby_session['Ingredient']

    # Return bottle template for landing page
    return bottle.template('herby_landing_2', app=flash_app, inventory=inventory, ingredients=ingredients)`

In regards to the redirect, I understand it returns a 0 sized redirect, but what I want is to redirect to the URL and still perform the function associated with it along with loading the template. Otherwise the table that my template creates will load old information.

**Comment by defnull** [comment]
Just a guess, but some db decorators (`pony.orm.db_session` in your case) perform a rollback if they encounter an exception. This is not what you want in case of `HTTPResponse` exceptions. You could catch-and-return the `HTTPResponse` thrown by `redirect()` to work around this, or instruct your ORM to not rollback when this exception is raised, or verify that the `pony.orm.commit()` actually does a full commit and not only a partial commit of a nested transaction.

Since this is not a bottle bug (`redirect()` does what it is supposed to do) and I can only guess what the rest of your application does or why DB updates are not persisted correctly, I'll close this issue.

**Comment by Xenonheat** [comment]
Thanks that gave me some insight.
