### ISSUE TITLE
Templates predence with "mount"

### ISSUE THREAD

**Issue by wonkydonky** [bottlepy/bottle#1053]
If, for example, I "mount" a Bottle app to `/user`

- does the mounted app work as a standalone app, completely isolated from the root app and other mounted apps?
- does the mounted app still have access to the root templates? In other words, can I do `{% extends 'base_layout.html' %}` from a mounted app while 'base_layout.html' is a template in the root app?

**Comment by defnull** [comment]
The mounted app is independent from the root app (e.g. plugins installed in the root app do not apply to the mounted app by default), but: Some state is global to the entire python process and not module bound. For example, the current working directory is global, and the global `template()` helper uses a globally configured paths to search for templates, which in turn contains relative paths resolved against the current working directory.

To get per-module template lookup to work, you can use `functools.partial` to build a customized `template()` function that overrides the global lookup path:

    local_templates = os.path.join(os.path.dirname(os.path.abspath(__file__), "views")
    template_lookup = [local_templates] + bottle.TEMPLATE_PATH
    template = functools.partial(bottle.template, template_lookup=template_lookup )

As long as the root module paths are also in this list, they can be extended or included as usual.
