### ISSUE TITLE
Steps to move from run() tornado server to https enabled tornado server

### ISSUE THREAD

**Issue by jjroelofs** [bottlepy/bottle#1067]
I have a bottle configuration that currently uses the tornado server like this:

`run(server='tornado', host='0.0.0.0', port=8082, debug=True)`

I understand from issue #594 that the run() implementation does not and will not support SSL, is that still true? because nowadays it's common for everything to go over https.

If this is true what are the steps to implement tornado with ssl? The documentations' deployment page is unclear to me regarding this topic. Thx for your time

**Comment by ghonchesefidi** [comment]
Same problem here

**Comment by defnull** [comment]
It is recommended to use nginx or a similar reverse-proxy for TSL offloading in production. Doing TSL in-process is a very specific requirement (e.g. to be able to validate client certificates) and requires more flexibility that the `run()` convenience function can provide. Setting up tornato with TSL and bottle as a WSGI app is covered in the tornado documentation. If the docs need improvement in this regard, then PRs are welcomed.
