### ISSUE TITLE
login

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [bottlepy/bottle#1074]
What is the preferred way to implement login/authentication in Bottle? Something like

        @route()
        @require_authentication
        def index():
            return "Restricted Area"

**Comment by agalera** [comment]
you can use a plugin

https://github.com/agalera/bottlejwt

**Comment by yoooooooooooooooooooooooo** [comment]
Does JWT require JavaScript? I don't understand how `bottlejwt` works... It creates a new token for me when calline `encode`, but then what am I supposed to do? Do I have to store the token in a cookie or in the localStorage? And how do I set the `Authorization` header before sending a new request?

**Comment by agalera** [comment]
@yoooooooooooooooooooooooo  

everything about jwt you have it on the official website
https://jwt.io/

This may be useful for you:
https://jwt.io/introduction/

**Comment by yoooooooooooooooooooooooo** [comment]
Yes what I don't understand is if I have to use JavaScript to set the `Authorization` header or if `bottlejwt` is supposed to do everything for me...

**Comment by agalera** [comment]
you must send the Authorization to the api through javascript, you must do it yourself. You can store the jwt token in the local storage
