### ISSUE TITLE
A question about "request"

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [bottlepy/bottle#1077]
from bottle import request
        
        @get('/')
        def index():
            return request.fullpath

if I understand correctly, when using Bottlepy with WSGI the app is only started once. If `request` is set at each HTTP request, how can Bottle distinguish between two different requests? In other words, if I'm processing 2 requests in parallel, how can `request` inside `index()` know which one is which without interference between the two?

**Comment by agalera** [comment]
bottle uses local threading to do this :)
https://docs.python.org/2/library/threading.html#threading.local

_local_property
https://github.com/bottlepy/bottle/blob/master/bottle.py#L1897

LocalRequest
https://github.com/bottlepy/bottle/blob/master/bottle.py#L1914

    """ A thread-local subclass of :class:`BaseRequest` with a different
        set of attributes for each thread. There is usually only one global
        instance of this class (:data:`request`). If accessed during a
        request/response cycle, this instance always refers to the *current*
        request (even on a multithreaded server). """

related problems:
https://github.com/bottlepy/bottle/issues/896

**Comment by yoooooooooooooooooooooooo** [comment]
Thanks!
