### ISSUE TITLE
CGI not working

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [bottlepy/bottle#1078]
I'm trying to deploy bottle on a shared host with Apache and CGI.

        .htaccess
        ---------
        Options +ExecCGI
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ app.py/$1 [L]

        app.py
        ------
        #!./venv/bin/python3
        
        from wsgiref.handlers import CGIHandler
        from myapp import app
        CGIHandler().run(app)

        myapp.py
        --------
        from bottle import route, run, template
        
        app = bottle.app ()
        
        @route ('/')
        def index ():
            return "Hello!"

For some reasons this doesn't work, and I don't understand why. Unfortunately I only get a `500 Internal Server Error` message and I cannot read the webserver logs. I've tried with Flask and it seems to work OK (no errors):

        myapp.py
        --------
        from flask import Flask
        
        app = Flask(__name__)
        
        @app.route('/')
        def index ():
            return "Hello World!"
        
        @app.route('/hello/<name>')
        def hello(name):
            return 'hello ' + name

Any idea? It looks like bottle is not creating the right output for CGI but I'm not sure... what can I try to fix this and get bottle working with CGI?

Thanks.

**Comment by Jwink3101** [comment]
See the bottom of https://bottlepy.org/docs/dev/deployment.html for how they suggest to use CGI. 

Also, apropos of your previous question on request, I am pretty sure when bottle is run as cgi, each and every request is a brand new instance that comes up and then shuts down when finished. So that answer may not apply. (Assuming I am correct here)

**Comment by yoooooooooooooooooooooooo** [comment]
@Jwink3101 yes I saw that, but I don't really know how to use it... Adding the line `bottle.run(server='cgi')` doesn't seem to fix anything.

**Comment by defnull** [comment]
This is hard to fix without error output from the server. If your hoster does not give you access to the webserver error logs, then you should probably find a better hoster.

Calling `bottle.run(server='cgi')` sets up `CGIHandler` for you. Doing that twice won't work. Either call `bottle.run(server='cgi')`, **or** setup `CGIHandler` yourself. You can't do both.

**Comment by yoooooooooooooooooooooooo** [comment]
The app

        myapp.py
        --------
        from bottle import route, run, template
        
        app = bottle.app ()
        
        @route ('/')
        def index ():
            return "Hello!"
        
        run (server='cgi')

runs OK locally on my PC, but when I upload it on the server I get a `500`. I contacted support and apparently the error in their logs is `ImportError: No module named bottle`. I do have installed the python `virtualenv`... is there a `PATH` missing somewhere?
