### ISSUE TITLE
Logo license

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [bottlepy/bottle#1084]
What is the license of the logo?

**Comment by defnull** [comment]
The License is basically this:

> It is allowed to use the logo as a link to the bottle homepage or in direct context with the unmodified library. In all other cases, please ask first.

So, basically, the logo can be used in any media (articles, tutorials, blog posts, slides, even print media) as long as it refers to the bottle framework. You cannot use it as the logo for something else (e.g. a fork) or without context. If in doubt, just ask. I have scale-able versions (svg) for high resolution prints or graphics if needed.
