### ISSUE TITLE
request.json doesn't raise HTTPError if the request body isn't valid json

### ISSUE THREAD

**Issue by Fulgen301** [bottlepy/bottle#1089]
https://github.com/bottlepy/bottle/blob/master/bottle.py#L1296 should raise an error if the content type is set to `application/json` and the body doesn't contain valid json. Instead, the function returns `None`.

**Comment by defnull** [comment]
Do you have `ujson` installed? The default `json_loads` (which is just `json.loads`) raises the correct exception.

**Comment by Fulgen301** [comment]
I don't.

**Comment by defnull** [comment]
Ahh, bottle-0.12. That's fixed in master already.

**Comment by Fulgen301** [comment]
Ah, then I'll try out master!

**Comment by Fulgen301** [comment]
Can confirm, works as expected with master.
