### ISSUE TITLE
load specific files in certain page in Bottlepy

### ISSUE THREAD

**Issue by ghonchesefidi** [bottlepy/bottle#1090]
Hi guys
I have several templates in my app and in one of them I'm loading my Head tag and loading static files like css and JS on it.
Now, How can I load specific files in certain page? There are several functions in PHP to do this but I have no idea how to do it in Python and Bottle.
For example I just need to time.js just loads in www.mydomain.com/timeforall
Any kind of help is appropriated :)

**Comment by defnull** [comment]
Add the required logic to your head template. For example:

    % for js in setdefault('additional_js', []):
         <script type="text/javascript" src="//static/js/{{js}}"></script>
    % end 

Then you can pass a list of additional js files you need for a specific page to the template call:

    return template(..., additional_js=['time.js'])

But this is not really a bottle/python related issue. In PHP you'd have to do the same. PHP is just a template language with way to many built-in features, after all.
