### ISSUE TITLE
Deployment recommandation (use case : restful api)

### ISSUE THREAD

**Issue by waghanza** [bottlepy/bottle#1091]
Hi,

We have added `bottle` to [our benchmark](https://github.com/the-benchmarker/web-frameworks/pull/343), but I can see that there is **plenty** of `deployment` options
https://bottlepy.org/docs/dev/deployment.html#switching-the-server-backend

Because I use to work with `gunicorn`, I've just implemented `gunicorn` + `meinheld`.

Do you have any recommendation according to server backend option ?

Regards,

**Comment by defnull** [comment]
You can have a look at https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Python/bottle for inspiration. They use gunicorn+meinheld (or tornado in a pypy environment) and their setup is pretty much optimized.

**Comment by agalera** [comment]
if you use meinheld remember not to use this:
"""python
from meinheld import patch
patch.patch_all()
"""

**Comment by waghanza** [comment]
what does this mean ?

**Comment by agalera** [comment]
@waghanza https://github.com/bottlepy/bottle/issues/896

**Comment by waghanza** [comment]
@agalera I observer a sligh increase with `meinheld` pacthing :+1: 

|  Framework  |         Average |  50th percentile |  90th percentile |  99th percentile | 99.9th percentile | Standard deviation |Requests / s |      Throughput |
|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|---------:|
|                      bottle  without patch                  | 22.20 ms | 18.46 ms | 36.79 ms | 65.80 ms | 258.73 ms | 13185.33 | 47305.00 | 116.32 MB | 
|                     flask    without patch                  | 54.14 ms | 51.70 ms | 65.02 ms | 129.30 ms | 792.09 ms | 33975.67 | 18632.00 | 45.79 MB |
 | bottle with patch                    | 24.13 ms | 16.22 ms | 41.84 ms | 109.57 ms | 411.66 ms | 22470.67 | 46868.00 | 115.21 MB |
 | flask     with pacth                | 54.69 ms | 47.05 ms | 77.58 ms | 125.59 ms | 727.20 ms | 28636.33 |18248.33 | 44.84 MB |
