### ISSUE TITLE
Redirect all traffic from Http to Https - Pybottle- Python 3

### ISSUE THREAD

**Issue by ghonchesefidi** [bottlepy/bottle#1092]
Hi guys
I have an app which is running on Https just fine but I need to redirect all my Http traffic to Https version. Now who request Http version got an error.
I had tried redirecting traffic using [Bottle SSLify](https://pypi.org/project/Bottle-SSLify/) but seams its not working on Python 3. I'm using Python 3.7 and Ubuntu latest version.
Any help is appropriated.  
Here is my app:
```python
from bottle import run, route, template, static_file, error, ServerAdapter
# ======== Start ======== Pages ========
@route('/')
def index():
    return template('./home/index')
# ======== End ======== pages ========

# ======== Start ======== Static files route ========
@route('/static/img/<filename:path>')
def img_static(filename):
    return static_file(filename, root='./static/img')
@route('/static/css/<filename:path>')
def css_static(filename):
    return static_file(filename, root='./static/css')
@route('/static/js/<filename:path>' )
def js_static(filename):
    return static_file(filename, root='./static/js')
# ======== End ======== Static files route ========

# ======== Start ======== Custom error pages ========
@error(404)
def error404(error):
    return template('./home/404')
# ======== End ======== Custom error pages ========

# ======== Start ======== SSL ========
class SSLWSGIRefServer(ServerAdapter):
    def run(self, handler):
        from wsgiref.simple_server import make_server, WSGIRequestHandler
        import ssl
        if self.quiet:
            class QuietHandler(WSGIRequestHandler):
                def log_request(*args, **kw): pass
            self.options['handler_class'] = QuietHandler
        srv = make_server(self.host, self.port, handler, **self.options)
        srv.socket = ssl.wrap_socket (
        	srv.socket,
        	certfile='ssl.pem',
        	server_side=True)
        srv.serve_forever()
srv = SSLWSGIRefServer(host="127.0.0.1", port=8090)
# ======== End ======== SSL ========
if  __name__ == '__main__':
    run(reloader=True,debug=True,server=srv)
```

**Comment by defnull** [comment]
Bottle itself does not handle SSL or cares about the protocol the request was issued with. You need to configure your HTTP server to also listen to the HTTP port, and then either use features of the HTTP server or a small WSGI middleware to redirect users to HTTPS for all requests. But please note:

* I strongly suggest using a reverse proxy (e.g. nginx) for SSL offloading, for both performance and security reasons. Also, `wsgiref` is not meant for production use, only for testing, even if used behind a reverse proxy.
* Accepting connections on HTTP is a security risk, as plain-text passwords may be submitted over unencrypted HTTP before the client is redirected. Most modern browsers default to HTTPS, so HTTP->HTTPS redirects should no longer be necessary.
* If you are using wsgiref just for testing, then it would make even more sense to not auto-redirect requests, so you notice errors in your application that would later expose users to unencrypted HTTP.

**Comment by ghonchesefidi** [comment]
Thanks for your great answer @defnull . I was using this app for production not testing ! good to know about wsgiref.

**Comment by ghonchesefidi** [comment]
@defnull I'm a little confused now. I understand when you told I should use middleware to redirect users to HTTPS but if now I don't have a web server how my app is running in https version? 
SSLWSGIRefServer is not my web server now?
Do you know how can I redirect my http traffic to https using current web server and not using Apache or Nginx ?
I want to first learn how to deploy my app completely then I will find a way how to handle a great web server 
:)
