### ISSUE TITLE
HTTP 2?

### ISSUE THREAD

**Issue by KristianDukov** [bottlepy/bottle#1095]
What is the current status on it? Does it work?

**Comment by tweenietomatoes** [comment]
You mean, you gonna use built-in server for action(production etc.)?

**Comment by tweenietomatoes** [comment]
I recommend you to use uwsgi + nginx instead.

**Comment by defnull** [comment]
Bottle does not implement HTTP or HTTP2, but WSGI. The network protocol is provided by the WSGI server implementation. Use one that implements HTTP2 (e.g. nginx+uwsgi).

Closed, out of scope.
