### ISSUE TITLE
a decorator for http parameters checking

### ISSUE THREAD

**Issue by changtimwu** [bottlepy/bottle#110]
Hi!
I'd like share some piece of code I wrote this morning.   Please let me know if this has been done before or you know how to do it better.

https://gist.github.com/746706

This decorator is very useful when writing an API server with bottle.  With this decorator, I saved  large amount of redundant code on parameter checking.

**Comment by nugend** [comment]
@defnull Is this something provided elsewhere? I stumbled on more or less the same idea from Giuseppe Tribulato and cleaned his implementation up a smidge:

https://gist.github.com/nugend/f56fa9b7bbddf2c56709

I find this pretty useful, personally.
