### ISSUE TITLE
won't start with pythonw

### ISSUE THREAD

**Issue by huangyanhan976** [bottlepy/bottle#1104]
I wrote a simple service, and tried to deploy it on windows. I used pythonw.exe to start the script. But bottle won't start. The process started and then quickly closed. But if I started it using python.exe, the process works fine. I think this might be a bug. The process won't start even if I just imported bottle but not doing anything. The code looks like this. pythonw hello_world.py would start, and then quickly shutdown.

```python
'''
hello_world.py
'''
import bottle
import time

if __name__ == '__main__':
    while True:
        print('Hello, world')
        time.sleep(2)
```
However,  python hello_world.py will do the work, and if I comment import bottle out, pythonw will do the job too.

**Comment by Jwink3101** [comment]
No. 

At least not without even the slightest bit to go on.

**Comment by Jwink3101** [comment]
You need to actually run the app. Look at the documentation for the sample and work from there

**Comment by huangyanhan976** [comment]
I am sorry if I didn't make myself clear.
I was saying that if I import the bottle moudle, the script would not start with pythonw.

if I run this command 
```bat
pythonw hello_world.py
```
the process started, and quickly ended.

but
```bat
python hello_world.py 
```
would do the trick.

It won't help if I change the python script, and start the app in the module like below.
```python
'''
hello_world.py
'''
import bottle
import time

app = bottle.Bottle()

@app.route('/')
def say_hello():
     return 'Hello, world!'


if __name__ == '__main__':
    app.run()
```

Would any body plz help me out?

**Comment by Jwink3101** [comment]
Isn’t pythonw just an alias for python? What are the error messages? Print out the sys.version and sys.executable information. 

If pythonw is not just an alias, are you 100% (!!!) certain that Bottle is installed for pythonw? Just as a diagnostic, download the bottle.py file and put it in the same folder as your script.

**Comment by defnull** [comment]
I suspect there is an `ImportError` you are not telling us about.

**Comment by defnull** [comment]
Actually, after reading about pythonw a bit (I'm not a windows user): `pythonw.exe` intentionally runs the python script in the background and immediately returns. It is designed to start GUI applications that want to hide the console window usually seen if you double-click on a python script in windows. This is why it looked like the script exited silently, while in fact, it was run detached from the console.

The problem is, without a console, `sys.stdin`, `sys.stdout` and `sys.stderr` are not available, and you won't see any stack traces. A `print` would actually throw an exception (python 2). It is really hard to debug scripts with `pythonw.exe`.

So, easy solution: Do not run bottle applications with `pythonw.exe`. I see no reason for supporting this strange use case.

**Comment by nolanl** [comment]
Running a server on windows is a pretty common use case for pythonw.exe (the other is GUI apps).  So there is good reason to run a bottle application without a console.

You can add:
```
sys.stdout = open('log.txt', 'w')
sys.stderr = open('err.txt', 'w')
```
to your app before you import bottle.

For some reason, nothing that gets written to stdout/stderr actually shows up in the files once bottle is imported, but aside from that it seems to work.

**Comment by seth-c-stenzel** [comment]
Here is my solution. The console starts but is then hidden by windows.

```
# Hide console window after start
import win32gui
import win32.lib.win32con as win32con
my_program = win32gui.GetForegroundWindow()
win32gui.ShowWindow(my_program , win32con.SW_HIDE)
```

You can then show the window again with:
```
# Show console window after hiding
win32gui.ShowWindow(my_program , win32con.SW_SHOW)
```

**Comment by seth-c-stenzel** [comment]
> Running a server on windows is a pretty common use case for pythonw.exe (the other is GUI apps). So there is good reason to run a bottle application without a console.
> 
> You can add:
> 
> ```
> sys.stdout = open('log.txt', 'w')
> sys.stderr = open('err.txt', 'w')
> ```
> 
> to your app before you import bottle.
> 
> For some reason, nothing that gets written to stdout/stderr actually shows up in the files once bottle is imported, but aside from that it seems to work.

This did not work for me with python 3.9.1

**Comment by josephernest** [comment]
@seth-c-stenzel For me it works on Python 3.8 and Windows, can you try on this version, just to be sure we are speaking about the same exact issue or something else?

```
sys.stdout = open('log.txt', 'w')
sys.stderr = open('err.txt', 'w')
```

**Comment by josephernest** [comment]
> So, easy solution: Do not run bottle applications with pythonw.exe. I see no reason for supporting this strange use case.

@defnull There are a few use cases for which Bottle should run in `pythonw.exe`. Example: you are doing a software with an HTTP API (using Bottle) and a GUI using browser in kiosk mode. When launching your app, you *don't* want a terminal/console with white font on black background to be displayed :)

Maybe it could be just a small fix in:

```
# Workaround for the "print is a keyword/function" Python 2/3 dilemma
# and a fallback for mod_wsgi (resticts stdout/err attribute access)
try:
    _stdout, _stderr = sys.stdout.write, sys.stderr.write
except IOError:
    _stdout = lambda x: sys.stdout.write(x)
    _stderr = lambda x: sys.stderr.write(x)
```

Maybe just adding this in `bottle.py`:

```
except:
    lambda *args: None
```

would solve this case.  @seth-c-stenzel does it work for you?

**Comment by seth-c-stenzel** [comment]
I'm sorry I don't have time to test this, as my workaround has been doing fine for me for a while now.

If I remember correctly, the issue here is just a threading issue and you'd need some way to call a .join on the bottle thread for pythonw.exe to stay open.

**Comment by josephernest** [comment]
@seth-c-stenzel In my case here is my observation:

* Calling `pythonw test.py` works and returns **immediately** in the console (this is normal!) but the `pythonw` process *is still running* (you can check in the Process manager):

    ![image](https://user-images.githubusercontent.com/6168083/181035576-4f61cb7c-ca77-4a5c-8c1e-14b531ff280a.png)

* You can browse to http://127.0.0.1:8080/random and you see it's still running as expected

* No need to use an extra thread or thread join(...) in my case

**Comment by seth-c-stenzel** [comment]
We appear to have different results. For instance, this code will work correctly with python.exe, not with pythonw.exe.

```
import bottle
import sys

sys.stdout = open('stdout.log', 'a+', buffering=1)
sys.stderr = open('stderr.log', 'a+', buffering=1)

app = bottle.Bottle()

@app.route('/')
def say_hello():
     return 'Hello, world!'

app.run(port=8888)
```

**Comment by defnull** [comment]
Bottle 0.12 grabs `sys.stdout.write` on import time so you have to replace `sys.stdout` before importing bottle. Or start pythonw with appropriate redirects (e.g. `pythonw.exe app.py 1>stdout.log 2>stderr.log`). Or start bottle with `run(..., quiet=True)`. Lots of options.

Current development version already silences errors while printing and should work out of the box. You would still crash your app as soon as the WSGI server tries to print something or log an error. There is nothing bottle could do about that.

**Comment by josephernest** [comment]
@seth-c-stenzel For it to work, you have to do it in this order:

```
import sys
sys.stdout = open('stdout.log', 'a+', buffering=1)
sys.stderr = open('stderr.log', 'a+', buffering=1)

import bottle

app = bottle.Bottle()

@app.route('/')
def say_hello():
     return 'Hello, world!'

app.run(port=8888)
```

Can you confirm it works for you?

**Comment by seth-c-stenzel** [comment]
The `quiet=True` option does not seem to resolve the issue or make any difference.

Overriding before the import does appear to resolve the issue. I doubt most people want to write to files, so I'm choosing to write out to null, which appears to work as expected.

```
import os
import sys
sys.stdout = open(os.devnull, 'a+', buffering=1)
sys.stderr = open(os.devnull, 'a+', buffering=1)

import bottle
import signal
from threading import Thread
import time

app = bottle.Bottle()


@app.route('/')
def return_hello():
    return 'Hello'

@app.route('/kill')
def handle_stop_request():
    Thread(target=shutdown_server).start()
    return 'Killing Server...'

def shutdown_server():
    time.sleep(2)
    pid = os.getpid()
    os.kill(pid, signal.SIGINT)

app.run(port=8888)
```

**Comment by seth-c-stenzel** [comment]
I'd like to apologize for wasting everyone's time. Looking back at my commits; it appears that I did not correctly override stdout/err before importing the bottle when I commented above that it did not work with Python version 3.9.1. 😞

**Comment by mentat51** [comment]
I'm trying to launch a bottle app as a service under windows 10.
And it's the same problem as running the app with pythonw, we don't have a stdout, stderr, etc...
I think bottle must handle this use case like with the patch of josephernest for example.
