### ISSUE TITLE
sameSite cookie attribute fails when using redirect

### ISSUE THREAD

**Issue by SlIdE42** [bottlepy/bottle#1106]
When setting a cookie and therefore using redirect, `sameSite` security attribute is not set but a falsy second cookie is created instead (with name `sameSite` and value `strict` or `lax`)... Even worse, if you use `secure` attribute, it's put on the wrong one.

You can reproduce it with the code below : 
1. Clean all cookies from localhost
2. Go to http://localhost:9000/ (meta redirect)
3. See one good cookie with `sameSite` attribute
4. Clean all cookies from localhost
5. Go to http://localhost:9000/?redirect (HTTP redirect)
6. See two bads cookies without `sameSite` attribute...

It has been tested with the latest development version of Bottle, Firefox 62 and Chrome 69, on Linux and macOS.

By the way, thank you for this small but useful piece of code !

```python3
#!/usr/bin/python3

import bottle

@bottle.route('/')
def index():
    bottle.response.set_cookie('name', 'value', same_site='strict')

    if bottle.request.query.get('redirect') == None:
        return """<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Redirect</title>
    <meta http-equiv="refresh" content="0; URL=/cookie">
  </head>
  <body>
  </body>
</html>"""
    else:
        bottle.redirect('/cookie')

@bottle.route('/cookie')
def redirect():
    bottle.response.content_type = 'text/plain; charset=UTF8'
    return """Please clean all cookies before each run !

Cookies :
=========
{}

Good value : "name=value" (with sameSite set to strict)
Bad  value : "name=value; sameSite=strict" (two cookies without sameSite)
""".format(bottle.request.headers.get('Cookie'))

@bottle.route('/favicon.ico')
def favicon():
    bottle.response.status = 204
    return ""

if __name__ == '__main__':
    bottle.run(host='localhost', port=9000, debug=True)
```

**Comment by defnull** [comment]
If that is the case, then the way bottle copies cookies from one response instance to the next is flawed:  https://github.com/bottlepy/bottle/blob/master/bottle.py#L1683

**Comment by SlIdE42** [comment]
This could be easily fixed by replacing `same_site` and `same-site` by `samesite` (pull request #1107)
