### ISSUE TITLE
Automated testing of supported backends?

### ISSUE THREAD

**Issue by hartwork** [bottlepy/bottle#1117]
Hi!

Last time I checked support for multiple backends was broken. I did a superficial check for related tests in the repository now and didn't any, e.g. there is no test that backend `waitress` still works today. Am I missing something? Are there plans to get all backends covered by smoke tests at leasts? Are there tests that I am missing? Should I create a ticket for every backend I find broken?

Thanks and best, Sebastian

**Comment by defnull** [comment]
Backend integration tests proved to be very unstable on public CI systems (travis/circle) and reported a lot of false positives, so they were removed. If you find a way to test these in a more stable way, that would be great.

**Comment by hartwork** [comment]
> Backend integration tests proved to be very unstable on public CI systems (travis/circle) and reported a lot of false positives

@defnull could you elaborate on that? What kind of false positives? What kind of instability?

**Comment by defnull** [comment]
Spawing a new process with a running server listening on localhost, waiting up to 10 seconds for the port to open, and then sending a single HTTP request, failed randomly. For various reasons. Either timeouts or port conflicts or other issues. I'm not exactly sure.

**Comment by hartwork** [comment]
Let's find out :smiley: Found the code in `test/test_server.py` by now.

**Comment by hartwork** [comment]
@defnull #1118 is ready for a first round of review now. I'm happy to make adjustments. We'll need some decision for #1119 to move on.

**Comment by hartwork** [comment]
Closing as #1118 is merged by now. Please re-open as needed.
