### ISSUE TITLE
404 error on running this code

### ISSUE THREAD

**Issue by Nikhil1R** [bottlepy/bottle#1124]
from bottle import route, run 
@route(/hello) 
def hello(): 
return "Hello World!" 
run(host=localhost, port=8080, debug=True)

**Comment by defnull** [comment]
That is not the code you are running (syntax errors and uninitialized variables)

**Comment by 1estart** [comment]
You need quotes for '/hello' and 'localhost'. And then 'Hello World!' will  be localhost/8080/hello

**Comment by Stormx480** [comment]
`from bottle import route, run

@route('/hello/')
def index():
    return 'Hello World'

run(host='localhost', port=8080,  debug=True)`
