### ISSUE TITLE
download last stable

### ISSUE THREAD

**Issue by voxspox** [bottlepy/bottle#1135]
Hi, I just wanted to download (via script) the last stable version but I found no (stable) URI which points to the last *stable* version. The last dev version is easily accessible via https://bottlepy.org/bottle.py or the master branch.

Suggestion:
Manage your code (unstable versions) in the 'develop' branch and only merge stable versions into 'master' branch.

**Comment by defnull** [comment]
What's the use-case to download the latest stable release? If you do not care about API stability, you can use the master branch (which is always tested and usable). If you *do* care about API stability, then you should only fetch the newest patch for a known release (e.g. https://bottlepy.org/docs/0.12/bottle.py) and not automatically upgrade to a new release, even if its stable.

**Comment by defnull** [comment]
Oh, and https://bottlepy.org/docs/stable/bottle.py works. That is probably what you want :)

**Comment by voxspox** [comment]
The website says on the main page: *Install the latest stable release with pip install bottle or download bottle.py (unstable) into your project directory.* I conclude that there is a stable and an unstable version available. Usually the unstable/development version has new features and also bugs. When it becomes reliable it will become the new stable version.

Because the website says `master` is unstable and the bottle.py in master has version `0.13-dev` (there is an extra *dev*elopment in it) I did not expect what you said above: *the master branch (which is always tested and usable).*

Maybe you want to be more clear in the docs :)

Thanks for the stable link.

**Comment by defnull** [comment]
The thing is `master` *is* unstable. It may break at any time. But since I only push to master if all tests pass, that's usually not an issue. Anyway, `0.13` is released now and I hope to get new releases out of the door more quickly from now on, so people do not have to rely on the development version.
