### ISSUE TITLE
bottle website shows 404 error  

### ISSUE THREAD

**Issue by Nikhil1R** [bottlepy/bottle#1137]
hi there , can anyone solve this issue for bottle website 
here its code 
![Screenshot from 2019-03-18 23-08-43](https://user-images.githubusercontent.com/23690578/54550851-d363be80-49d2-11e9-8fa9-013bd046abe6.png)

and here the error appear when tried to enter the website on mozilla firefox-esr
![Screenshot from 2019-03-18 23-02-33](https://user-images.githubusercontent.com/23690578/54551015-2a699380-49d3-11e9-9624-def208882410.png)

and here that error apperearing in terminal window
![Screenshot from 2019-03-18 23-02-38](https://user-images.githubusercontent.com/23690578/54550927-f68e6e00-49d2-11e9-97a3-5d51b27de18f.png)

please suggest what should i do to run a website on kali linux

**Comment by defnull** [comment]
You do not define a route for `/`. Why do you expect bottle to return?

**Comment by Nikhil1R** [comment]
what should be the code for this

**Comment by defnull** [comment]
These questions are so basic that I strongly suggest you have a look at the documentation first. It's all covered there. If you have questions that is not covered by the documentation, please open a new issue so we can improve the documentation.

**Comment by sulinys** [comment]
If you declared route in code '/hello/h0n3y' then full url address is 'localhost:8080/hello/h0n3y'

**Comment by Nikhil1R** [comment]
now it shows this error
![Screenshot from 2019-03-18 23-41-18](https://user-images.githubusercontent.com/23690578/54553057-67378980-49d7-11e9-9052-9cc787b450f4.png)
how can this be fixed
