### ISSUE TITLE
Enter route if Authorization header set

### ISSUE THREAD

**Issue by needsearch** [bottlepy/bottle#1142]
Is it possible to activate a route only if a header is set? For example something like

        @route("/")
        @header("Authorization")
        def index():
            Enter here only if the "Authorization" HTTP header is present
        
        @route("/")
        def index():
            Enter here if there is no "Authorization" HTTP header

**Comment by Jithinqw** [comment]
You could write a decorator for python place it on the router, which can reject or accept a request if the header is set.

```
@route('/')
@check_for_header
def index():
     < Your logic here >
```

**Comment by agalera** [comment]
I needed the same, and I made a plugin to add arguments in the routing
```python
@get("/", auth="any values and types")
def example(auth):  # auth argument is optional!
    return "ok"
```
lib: https://github.com/agalera/bottlejwt
plugin code: https://github.com/agalera/bottlejwt/blob/master/bottlejwt.py

only need this in your plugin:
```python
    def apply(self, callback, route):
        auth_value = route.config.get(self.keyword, None)
        if not auth_value:
            return callback
```

**Comment by defnull** [comment]
You can shield a route from unauthorized access with a decorator or plugin, or forward requests to a more suitable handler function based on any criteria you like. But it is currently not possible to actually route requests based on anything other than method and path. The router does not take headers into account. If you need this special kind of functionality, you can always implement it directly in your own request handler functions, or automate it with a plugin.
