### ISSUE TITLE
Add type hitting in next release

### ISSUE THREAD

**Issue by iamybj** [bottlepy/bottle#1145]
I recommend that add type hitting in next release.
And also, I think the code of bottle is too complex. It can be more clean and simple.

**Comment by defnull** [comment]
Then improve it? Pull requests welcomed.

But as said in other issues: I will not accept large patches that were generated by automated tools like black or other pep-8 auto-formatters, or patches that touch large areas of the file. These destroy the source history and make `git blame` useless. Small patches that improve specific parts of the project (not just formatting) are welcomed, though.
