### ISSUE TITLE
redirect() and non-ascii characters

### ISSUE THREAD

**Issue by sharpaper** [bottlepy/bottle#1148]
This is a continuation of #792 that was recently closed. These are the exact steps to reproduce the bug:

Create a file `test.py`

    import bottle
    from bottle import get, redirect
    
    @get("/<name>")
    def user(name):
        return name
    
    @get("/")
    def index():
        return redirect("/à")

Start server `python3 -m bottle --bind 127.0.0.1:8081 test`

Go to `http://localhost:8081`, it should redirect to `http://localhost:8081/à`.

This seems to work without problems with Bottle 0.13-dev but **not** for the current 0.12.x releases. With Bottle `0.12.16` I get an error, `Error: 400 Bad Request Invalid path string. Expected UTF-8`.

**Comment by defnull** [comment]
Ahh, there it is. The 0.12 release needs a backport of c0b3c0d9 (and some more). That's a different issue than the two you were referring to earlier, but still a valid issue.

**Comment by sharpaper** [comment]
I probably misreported it because I was having this issue but couldn't figure out the problem, and searching the web I ended up on those two old threads. It all seems to be fixed in 0.13-dev, but it would be very useful to have it fixed in the next 0.12.17 minor release too because it's pretty significant (unless of course you're planning to release 0.13 next). Thank you very much.

**Comment by defnull** [comment]
Fix was easy, but I can not release from the PC I am currently on. Will push a release this evening or Friday.

**Comment by sharpaper** [comment]
Sure no problem! When you have the time of course :)
Thank you very much!
