### ISSUE TITLE
template(source='...') "argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by sharpaper** [bottlepy/bottle#1152]
from bottle import route, run, template
    
    @route('/')
    def index():
        return template(source='lorem ipsum')

This returns the error  `TypeError: argument of type 'NoneType' is not iterable`. Isn't `source=` supposed to render a string without looking for a template file?

**Comment by defnull** [comment]
There is no `source` keyword argument in `template()`. The first positional argument is interpreted as a template string (if it contains special characters), or as a template name (if not).
