### ISSUE TITLE
view decorator with None result

### ISSUE THREAD

**Issue by zhangyoufu** [bottlepy/bottle#1157]
https://github.com/bottlepy/bottle/blob/357a0cb39cb8337f8467f5396e4b7caaa7e4f25c/bottle.py#L4247-L4273

I think it should be `return template(tpl_name, **defaults)` instead of `return template(tpl_name, defaults)` for the `result is None` branch.

**Comment by defnull** [comment]
This is actually how it's implemented in recent versions
