### ISSUE TITLE
date formatting for non-English locale

### ISSUE THREAD

**Issue by zhangyoufu** [bottlepy/bottle#1159]
https://github.com/bottlepy/bottle/blob/0dd195111621b4db5e9b7d5e5852fab3c6270098/bottle.py#L2951-L2958
https://github.com/bottlepy/bottle/blob/0dd195111621b4db5e9b7d5e5852fab3c6270098/bottle.py#L1875-L1880

`%a` and `%b` are locale-dependent. See also #1009.

**Comment by defnull** [comment]
The fix for #1009 should work here, too, no?

**Comment by zhangyoufu** [comment]
For compatibility, naive `datetime.datetime` & `datetime.date` is treated as UTC time.

A user might be surprised that `bottle.http_date(datetime.datetime.now())` does not work out-of-box.
