### ISSUE TITLE
json-lines supporting?

### ISSUE THREAD

**Issue by fengyong** [bottlepy/bottle#1164]
when i writing an reverse proxy to grafana , i found the body format is described as ''application/json", but it is really json-lines formatted, i have to manually parse the body use json_lines: 
 `json_lines.reader(request.body)`

will bottle offer a method: json_lines() method when try to call  json() failed?

**Comment by defnull** [comment]
Probably not. There are all kinds of json dialects (json-lines is actually not valid json) and supporting all of them is out of scope for a micro-framework. Plus, this is really easy to do in a one-liner, as you already found out.

You could also write a plugin that adds this functionality by the way, if you need it a lot in your application.
