### ISSUE TITLE
Unicode encoding not working with <form enctype="multipart/form-data">

### ISSUE THREAD

**Issue by sharpaper** [bottlepy/bottle#1165]
**Problem**: when using `<form enctype="multipart/form-data">`, FormsDict does not return the correct unicode values for input fields.

**How to reproduce**:

    from bottle import route, run, template, get, post, request
    
    @get('/')
    def index():
            return """
            <form method="post" enctype="multipart/form-data">
                <input type="text" name="key" />
                <input type="submit" />
            </form>
            """
    
    @post('/')
    def index_post():
        print(request.forms['key'])
        print(request.forms.get('key'))
        print(request.forms.key)
        print(request.forms.getunicode('key'))
        return ""

`index_post` output:

    cérémonie
    cérémonie
    
    None

**but** if you remove `enctype="multipart/form-data"` the output is magically correct:

    cÃ©rÃ©monie
    cÃ©rÃ©monie
    cérémonie
    cérémonie

What is going on? Is this the correct behavior? I don't really understand if it's a bug or not...

**Comment by sharpaper** [comment]
The explanation here could be that `application/x-www-form-urlencoded` the POST body is URL-encoded just like a GET query string, whereas `multipart/form-data` **is not** URL-encoded. So I think it's a Bottle bug because it tries to encode a string that is already in UTF-8?

**Comment by defnull** [comment]
The issue was fixed in master ( see #1111 and  5813b87 ) but not back-ported to 0.12 yet.

**Comment by sharpaper** [comment]
Is Bottle 0.13 available on pypi?

**Comment by defnull** [comment]
Backportet to 0.12.24
