### ISSUE TITLE
The secret parameter for set_cookie is broken for Python 3.8

### ISSUE THREAD

**Issue by rhettinger** [bottlepy/bottle#1171]
See:  https://bugs.python.org/issue33604

The fix is simple.  Add `digestmod='sha256' to the *hmac_new* call here:
```
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bottle.py", line 2600, in cookie_encode
        sig = base64.b64encode(hmac.new(tob(key), msg).digest())
```

**Comment by defnull** [comment]
Signing new cookies with sha256 should be fine. But if md5 was the default, then decoding should still support cookies that were signed with it. Otherwise, a bottle update would e.g. logout all users of an application at once. Or am  missing something?

**Comment by oz123** [comment]
@rhettinger the issue does not exist with dev version, since it uses the sha256 method:
https://github.com/bottlepy/bottle/blob/master/bottle.py#L3055.
This the default is:
```digestmod = digestmod or hashlib.sha256```

**Comment by rhettinger** [comment]
Thanks.
