### ISSUE TITLE
Add SameSite=None support in set_cookie

### ISSUE THREAD

**Issue by yoch** [bottlepy/bottle#1174]
Hi,

The latest RFC [introduces](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-5.3.7) a third option 'None' for SameSite, which is currently not supported.
In fact, all values but 'lax' and 'strict' must be treated as 'none'.

Regards

**Comment by defnull** [comment]
Isn't `SameSite=None` equivalent to not setting this attribute at all?

**Comment by provinzkraut** [comment]
As far as I understand, since [no behaviour is defined](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-5.3.7.1) for the value `none`, it *is* the same as not setting it at all.

**Comment by yoch** [comment]
Not in practice, because some browsers (like [chrome](https://www.chromestatus.com/feature/5088147346030592) or firefox) define [SameSite=Lax by default](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00).

Its not difficult to implement, I'll send a PR.

BTW, it is possible tu have this feature enabled in 0.12 ?
