### ISSUE TITLE
Jquery files doesn't load as server launch

### ISSUE THREAD

**Issue by 0xh0n3y** [bottlepy/bottle#1176]
Here's the code:
"""
piweather.py

A Web based Temperature/Humidity monitor using Raspberry Pi and DHT11.

Author: Mahesh Venkitachalam
"""

from bottle import route, run, request, response
from bottle import static_file
import random, argparse
import RPi.GPIO as GPIO
from time import sleep  
import Adafruit_DHT

@route('/hello')
def hello():
    return "Hello Bottle World!"

@route('/<filename:re:.*\.js>')
def javascripts(filename):
    return static_file(filename, root='flot')

@route('/static/:filename:')
def send_static(filename):
    return static_file(filename, root='./static/home/pi/myProjectDir/jquery.js')

@route('/static/:filename:')
def send_static(filename):
    return static_file(filename, root='./static/home/pi/myProjectDir/jquery.flot.js')

@route('/static/:filename:')
def send_static(filename):
    return static_file(filename, root='./static/home/pi/myProjectDir/jquery.flot.time.js')

@route('/plot')
def plot():
    return '''
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>PiWeather</title>
    <style>
     .demo-placeholder {
	width: 90%;
	height: 50%;
    }
    </style>
	<script language="javascript" type="text/javascript" 
       src="/static/pi/myProjectDir/jquery.js"></script>
	<script language="javascript" type="text/javascript" 
       src="/static/pi/myProjectDir/jquery.flot.js"></script>
    <script language="javascript" type="text/javascript" 
       src="/static/pi/myProjectDir/jquery.flot.time.js"></script>
    <script language="javascript" type="text/javascript">

$(document).ready(function() {

    // plot options
    var options = {
        series: {
		  lines: {
			show: true
		  },
		  points: {
			show: true
		  }
		},
        grid: {
		  clickable: true
		},
	    yaxes: [{min: 0, max: 100}],
        xaxes: [{min: 0, max: 100}],
    };
    
    // create empty plot
	var plot = $.plot("#placeholder", [[]], options);

    // initialize data arrays
    var RH = [];
    var T = []; 
    var timeStamp = [];    
    // get data from server
    function getData() {
        // AJAX callback
        function onDataReceived(jsonData) {    
            timeStamp.push(Date());
            // add RH data
			RH.push(jsonData.RH);
            // removed oldest
            if (RH.length > 100) {
              RH.splice(0, 1);
            }
            // add T data
            T.push(jsonData.T);
            // removed oldest
            if (T.length > 100) {
              T.splice(0, 1);
            }
            s1 = [];
            s2 = [];
            for (var i = 0; i < RH.length; i++) {
                s1.push([i, RH[i]]);
                s2.push([i, T[i]]);
            }
            // set to plot
            plot.setData([s1, s2]);
            plot.draw();
		}

        // AJAX error handler
        function onError(){
            $('#ajax-panel').html('<p><strong>Ajax error!</strong> </p>');
        }
        
        // make the AJAX call
		$.ajax({
		    url: "getdata",
			type: "GET",
			dataType: "json",
			success: onDataReceived,
            error: onError
		});        
     }

     // define an update function
	 function update() {
        // get data
        getData();
        // set timeout
		setTimeout(update, 1000);
	 }

     // call update
	 update();
 
     // define click handler for LED ctrl
     $('#ckLED').click(function() {
         var isChecked = $("#ckLED").is(":checked") ? 1:0;
         $.ajax({
           url: '/ledctrl',
           type: 'POST',
           data: { strID:'ckLED', strState:isChecked }
         });
      });

     $("#placeholder").bind("plotclick", function (event, pos, item) {
          if (item) {
            plot.highlight(item.series, item.datapoint);
            var strData = ' [Clicked Data: ' + 
                           timeStamp[item.dataIndex] + ': T = ' + 
                           T[item.dataIndex] + ', RH = ' + RH[item.dataIndex]
                          + ']';
            $('#data-values').html(strData);
          }
     });
});

</script>
</head>

<body>
	<div id="header">
		<h2>Temperature/Humidity</h2>
	</div>

	<div id="content">
		<div class="demo-container">
			<div id="placeholder" class="demo-placeholder"></div>
		</div>
        <div id="ajax-panel"> </div>
	</div>
    <div>
      <input type="checkbox" id="ckLED" value="on">Enable Lighting.
      <span id="data-values"> </span>
    </div>
    
</body>
</html>
'''
    
@route('/getdata', method='GET')
def getdata():
    RH, T = Adafruit_DHT.read_retry(Adafruit_DHT.DHT11, 23)
    # return dict
    return {"RH": RH, "T": T}
    
@route('/ledctrl', method='POST')
def ledctrl():
    val = request.forms.get('strState')
    on = bool(int(val))
    GPIO.output(18, on) 

# main() function
def main():
    print 'starting piweather...'
    # create parser
    parser = argparse.ArgumentParser(description="PiWeather...")
    # add expected arguments
    parser.add_argument('--ip', dest='ipAddr', required=True)
    parser.add_argument('--port', dest='portNum', required=True)

    # parse args
    args = parser.parse_args()

    # setup GPIO
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(18, GPIO.OUT)
    GPIO.output(18, False)
    # start server
    run(host=args.ipAddr, port=args.portNum, debug=True)

# call main
if __name__ == '__main__':
    main()

Here's the error's:
pi@raspberrypi:~/myProjectDir $ sudo python piweather.py --ip localhost --port 8080
starting piweather...
Bottle v0.12.17 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

127.0.0.1 - - [30/Oct/2019 18:30:13] "GET /plot HTTP/1.1" 200 3468
127.0.0.1 - - [30/Oct/2019 18:30:16] "GET /static/pi/myProjectDir/jquery.js HTTP/1.1" 404 748
127.0.0.1 - - [30/Oct/2019 18:30:16] "GET /static/pi/myProjectDir/jquery.flot.js HTTP/1.1" 404 753
127.0.0.1 - - [30/Oct/2019 18:30:17] "GET /static/pi/myProjectDir/jquery.flot.time.js HTTP/1.1" 404 758
127.0.0.1 - - [30/Oct/2019 18:30:17] "GET /static/pi/myProjectDir/jquery.js HTTP/1.1" 404 748
127.0.0.1 - - [30/Oct/2019 18:30:18] "GET /static/pi/myProjectDir/jquery.flot.js HTTP/1.1" 404 753
127.0.0.1 - - [30/Oct/2019 18:30:18] "GET /static/pi/myProjectDir/jquery.flot.time.js HTTP/1.1" 404 758
127.0.0.1 - - [30/Oct/2019 18:30:21] "GET /favicon.ico HTTP/1.1" 404 742

please suggest something to fix this issue
![Screenshot from 2019-10-30 18-39-50](https://user-images.githubusercontent.com/23690578/67860862-019ea480-fb45-11e9-95be-115e39497b77.png)

it doesn't shows graph either of temperature and humidity just shows this above blank image even when the pi GPIO pins are attached with beardboard.

**Comment by 0xh0n3y** [comment]
even after removing /static and all changes required you mentioned had done but the error is persistent :
pi@raspberrypi:~/myProjectDir $ sudo python piweather.py --ip localhost --port 8080 starting piweather...
piweather.py:208: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(18, GPIO.OUT)
Bottle v0.12.17 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

127.0.0.1 - - [31/Oct/2019 16:34:31] "GET /plot HTTP/1.1" 200 3396
127.0.0.1 - - [31/Oct/2019 16:34:38] "GET /jquery.js HTTP/1.1" 404 725
127.0.0.1 - - [31/Oct/2019 16:34:39] "GET /jquery.flot.js HTTP/1.1" 404 730
127.0.0.1 - - [31/Oct/2019 16:34:39] "GET /jquery.flot.time.js HTTP/1.1" 404 735

get the code i used is:

"""
piweather.py

A Web based Temperature/Humidity monitor using Raspberry Pi and DHT11.

Author: Mahesh Venkitachalam
"""

from bottle import route, run, request, response
from bottle import static_file
import random, argparse
import RPi.GPIO as GPIO
from time import sleep  
import Adafruit_DHT

@route('/hello')
def hello():
    return "Hello Bottle World!"

@route('/<filename:re:.*\.js>')
def javascripts(filename):
    return static_file(filename, root='flot')

@route('/static/jquery')
def send_static(filename):
    return static_file(filename, root='/home/pi/myProjectDir/')

@route('/static/jquery.flot')
def send_static(filename):
    return static_file(filename, root='/home/pi/myProjectDir/')

@route('/static/jquery.flot.time')
def send_static(filename):
    return static_file(filename, root='/home/pi/myProjectDir/')

@route('/plot')
def plot():
    return '''
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>PiWeather</title>
    <style>
     .demo-placeholder {
	width: 90%;
	height: 50%;
    }
    </style>
	<script language="javascript" type="text/javascript" 
       src="jquery.js"></script>
	<script language="javascript" type="text/javascript" 
       src="jquery.flot.js"></script>
    <script language="javascript" type="text/javascript" 
       src="jquery.flot.time.js"></script>
    <script language="javascript" type="text/javascript">

$(document).ready(function() {

    // plot options
    var options = {
        series: {
		  lines: {
			show: true
		  },
		  points: {
			show: true
		  }
		},
        grid: {
		  clickable: true
		},
	    yaxes: [{min: 0, max: 100}],
        xaxes: [{min: 0, max: 100}],
    };
    
    // create empty plot
	var plot = $.plot("#placeholder", [[]], options);

    // initialize data arrays
    var RH = [];
    var T = []; 
    var timeStamp = [];    
    // get data from server
    function getData() {
        // AJAX callback
        function onDataReceived(jsonData) {    
            timeStamp.push(Date());
            // add RH data
			RH.push(jsonData.RH);
            // removed oldest
            if (RH.length > 100) {
              RH.splice(0, 1);
            }
            // add T data
            T.push(jsonData.T);
            // removed oldest
            if (T.length > 100) {
              T.splice(0, 1);
            }
            s1 = [];
            s2 = [];
            for (var i = 0; i < RH.length; i++) {
                s1.push([i, RH[i]]);
                s2.push([i, T[i]]);
            }
            // set to plot
            plot.setData([s1, s2]);
            plot.draw();
		}

        // AJAX error handler
        function onError(){
            $('#ajax-panel').html('<p><strong>Ajax error!</strong> </p>');
        }
        
        // make the AJAX call
		$.ajax({
		    url: "getdata",
			type: "GET",
			dataType: "json",
			success: onDataReceived,
            error: onError
		});        
     }

     // define an update function
	 function update() {
        // get data
        getData();
        // set timeout
		setTimeout(update, 1000);
	 }

     // call update
	 update();
 
     // define click handler for LED ctrl
     $('#ckLED').click(function() {
         var isChecked = $("#ckLED").is(":checked") ? 1:0;
         $.ajax({
           url: '/ledctrl',
           type: 'POST',
           data: { strID:'ckLED', strState:isChecked }
         });
      });

     $("#placeholder").bind("plotclick", function (event, pos, item) {
          if (item) {
            plot.highlight(item.series, item.datapoint);
            var strData = ' [Clicked Data: ' + 
                           timeStamp[item.dataIndex] + ': T = ' + 
                           T[item.dataIndex] + ', RH = ' + RH[item.dataIndex]
                          + ']';
            $('#data-values').html(strData);
          }
     });
});

</script>
</head>

<body>
	<div id="header">
		<h2>Temperature/Humidity</h2>
	</div>

	<div id="content">
		<div class="demo-container">
			<div id="placeholder" class="demo-placeholder"></div>
		</div>
        <div id="ajax-panel"> </div>
	</div>
    <div>
      <input type="checkbox" id="ckLED" value="on">Enable Lighting.
      <span id="data-values"> </span>
    </div>
    
</body>
</html>
'''
    
@route('/getdata', method='GET')
def getdata():
    RH, T = Adafruit_DHT.read_retry(Adafruit_DHT.DHT11, 23)
    # return dict
    return {"RH": RH, "T": T}
    
@route('/ledctrl', method='POST')
def ledctrl():
    val = request.forms.get('strState')
    on = bool(int(val))
    GPIO.output(18, on) 

# main() function
def main():
    print 'starting piweather...'
    # create parser
    parser = argparse.ArgumentParser(description="PiWeather...")
    # add expected arguments
    parser.add_argument('--ip', dest='ipAddr', required=True)
    parser.add_argument('--port', dest='portNum', required=True)

    # parse args
    args = parser.parse_args()

    # setup GPIO
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(18, GPIO.OUT)
    GPIO.output(18, False)
    # start server
    run(host=args.ipAddr, port=args.portNum, debug=True)

# call main
if __name__ == '__main__':
    main()

**Comment by 0xh0n3y** [comment]
Can you please the post the edited code?

**Comment by 0xh0n3y** [comment]
Can you plz post edited code?

**Comment by Marrin** [comment]
Can you please post code formatted as code and reduce the example to the minimum. The GPIO stuff has nothing to do with the problem.  In fact the example should have just one route to deliver HTML that references _one_ static file, and one route that delivers static files from a folder.  There is no need to write one route for each JavaScript file manually.

How to [serve static files from a folder is described in the dokumentation](http://bottlepy.org/docs/dev/tutorial.html#static-files).

**Comment by 0xh0n3y** [comment]
This code is creating error :

<title>PiWeather</title>
 <style> .demo-placeholder {
      width: 90%; 
      height: 50%; } 
</style>
<script language="javascript" type="text/javascript" src="jquery.js"></script> <script language="javascript" type="text/javascript" src="jquery.flot.js"></script>
<script language="javascript" type="text/javascript" src="jquery.flot.time.js"></script>
<script language="javascript" type="text/javascript">

How should i edit this code to work ?

**Comment by 0xh0n3y** [comment]
When firstly i had used this code it showed the same error?
https://raw.githubusercontent.com/electronut/pp/master/piweather/piweather.py

**Comment by 0xh0n3y** [comment]
These jquery files are being used in this code and that are needed to be loaded at the time of server host the website at localhost:8080/plot .
