### ISSUE TITLE
Regex defect in class StplParser where backslashes are not escaped in release 0.12.*

### ISSUE THREAD

**Issue by ahendley** [bottlepy/bottle#1177]
Have on a number of occasions had to fix the constructed regex in the class StplParser so bottle will work.

Lines 3433 and 3434 are the culprits in this instances where the string has not been declared as a regex ( r'' ).

For each backslash I have had to update these with;

```python
_re_tok += '|([\\[\\{\\(])'
_re_tok += '|([\\]\\}\\)])'
```

**Comment by defnull** [comment]
Should be fixed by now (0.12.18). Thanks
