### ISSUE TITLE
Bottle fails to find templates on windows

### ISSUE THREAD

**Issue by defufna** [bottlepy/bottle#1186]
Consider this simple sample:

```
import bottle

@bottle.route("/")
@bottle.view("test")
def test():
    return {}

bottle.run()
```

This sample will fail to find test.tpl on windows. It will fail for both ./ and ./view/. The reason is because os.path.abspath behavior is slightly different on windows and linux. On windows abspath preserves ending path separators, while on linux it doesn't. So on windows abspath("./") returns "C:\projects\test\\" while on linux it returns "/home/user/projects/test" (note the missing separator).

So when these expanded paths encounter [this line](https://github.com/bottlepy/bottle/blob/master/bottle.py#L3846) in bottle. 
`spath = os.path.abspath(spath) + os.sep`

On windows we get a path that ends with two separators. This causes [this if](https://github.com/bottlepy/bottle/blob/master/bottle.py#L3848) to always fail.

`if not fname.startswith(spath): continue`

This leads to all path probes failing on windows, and template never gets found.

**Comment by defnull** [comment]
You sure about the `abspath` behavior? I do not have a windows VM at hand to test it, but I'd suspect that the actual bug might be: `os.sep` is a backslash on windows, but `abspath()` normalizes to forward slashes. Using `+ os.sep` produces a mixed path. Switching to `join(path, "")` would help.

**Comment by defnull** [comment]
Tested it with `ntpath` on linux. `ntpath.abspath()` removes the leading slash, as expected. The bug was that `os.sep` is platform dependent, but `abspath()` always normalizes to forward slashes. Fixed in master now (hopefully). Could you please verify?

**Comment by defufna** [comment]
I tried it on windows, unfortunately it doesn't work. This is what I get.

```
Traceback (most recent call last):
  File "d:\Development\python\bottletest\bottle.py", line 1005, in _handle
    out = route.call(**args)
  File "d:\Development\python\bottletest\bottle.py", line 2017, in wrapper
    rv = callback(*a, **ka)
  File "d:\Development\python\bottletest\bottle.py", line 4273, in wrapper
    return template(tpl_name, **tplvars)
  File "d:\Development\python\bottletest\bottle.py", line 4242, in template
    TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
  File "d:\Development\python\bottletest\bottle.py", line 3826, in __init__
    raise TemplateError('Template %s not found.' % repr(name))
bottle.TemplateError: Template 'test' not found.
```

For test purpose, I've added `print(spath, fname)` right after [line 3844](https://github.com/bottlepy/bottle/blob/48e9dfef69d94d1acabb46cd6976acfcc214377b/bottle.py#L3844). And this is what I get:

```
D:\Development\python\bottletest\/ D:\Development\python\bottletest\test
D:\Development\python\bottletest\views\/ D:\Development\python\bottletest\views\test

```

**Comment by defnull** [comment]
I've read https://docs.python.org/3/library/os.path.html#os.path.normpath backwards. `abspath` normalizes slashes to `os.sep`, which is a backslash on windows. It does remove leading slashes, though.

    >>> ntpath.abspath("D:\\Development\\python\\bottletest\\")
    'D:\\Development\\python\\bottletest'
    >>> ntpath.abspath("D:\\Development\\python\\bottletest")
    'D:\\Development\\python\\bottletest'
    >>> ntpath.abspath("D:\\Development\\python\\bottletest/")
    'D:\\Development\\python\\bottletest'

Now I am not longer sure why the previous solution (`abspath + os.sep`) was an issue in the first place. It should work as expected (produce an absolute path with a leasing OS-normalized slash). We'll have to revert the fix and see what actually is going on.

**Comment by defnull** [comment]
Which version of python are you using?

**Comment by defufna** [comment]
Wow it seems like my python is the problem. I'm using: 
`3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)`

I tried the same sample with other versions of Python I have, and they all behave differently from 3.7.1. Here take a look:

```
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)
D:\Development\python\bottletest/ D:\Development\python\bottletest\test
D:\Development\python\bottletest\views/ D:\Development\python\bottletest\views\test

3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)
D:\Development\python\bottletest\/ D:\Development\python\bottletest\test
D:\Development\python\bottletest\views\/ D:\Development\python\bottletest\views\test

3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)
D:\Development\python\bottletest/ D:\Development\python\bottletest\test
D:\Development\python\bottletest\views/ D:\Development\python\bottletest\views\test

2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)
('D:\\Development\\python\\bottletest/', 'D:\\Development\\python\\bottletest\\test')
('D:\\Development\\python\\bottletest\\views/', 'D:\\Development\\python\\bottletest\\views\\test')
```
So the original code would work with different python. Sorry for wasting your time...

**Comment by defnull** [comment]
You were bitten by this I think: https://github.com/python/cpython/pull/10082
