### ISSUE TITLE
Advice on running Bottle on Windows

### ISSUE THREAD

**Issue by apournaras** [bottlepy/bottle#1199]
Hi,
I am running a REST web service on a windows 10 PC that gets some decent traffic, but nothing extreme. I am using twisted as a WSGI server. I am running everything on conda. The issue I am having is that sometimes the web service freezes, it doesn't process any new requests. I am having this problem for a long time and every time I am forced to restart the service as I can't figure out what goes wrong. Has anyone experienced anything similar on Windows? What is a good solution for a production-ish use of bottle with Windows?

**Comment by syegulalp** [comment]
It's been a while since I did this, but if you're using WSGI in conjunction with IIS, it's likely that the IIS threadpool is being exhausted. How are you hosting Bottle?

**Comment by apournaras** [comment]
I am not using IIS. I am only using twisted with Bottle

**Comment by defnull** [comment]
The default thread-pool created by bottle for twisted has 5 to 20 threads. If you are blocking 20 threads, no new requests can be handled. Slow or misbehaving clients, or unhandled errors might also cause the server to stop responding. But this is a question besser suited for a twisted mailing-list or forum. Bottle is 'just' a WSGI framework and does not manage or create threads on its own.
