### ISSUE TITLE
"Allow" header value on 405 responses is still incorrect despite the issue being fixed in the master branch

### ISSUE THREAD

**Issue by PLPeeters** [bottlepy/bottle#1225]
The value of the `Allow` header on 405 responses is still incorrect despite it being fixed by #668, which was merged into `master` in 3b09891fc516e9d1f9fe578d7e06208dc688e378 almost three years ago.

How come this didn't make it into releases 0.12.14 and later?

**Comment by defnull** [comment]
No one bothered backporting it. Most clients just ignore this header, so this fix is not important for most people, as it seems. Pull requests (against the release-0.12 branch) are welcomed.

**Comment by PLPeeters** [comment]
Good to know, I'll PR it in the 0.12 branch!

**Comment by PLPeeters** [comment]
@defnull Is there a chance of getting a merge on this sometime soon?
