### ISSUE TITLE
DELETE method not found on Ubuntu 16.04

### ISSUE THREAD

**Issue by marianlukac** [bottlepy/bottle#1227]
Do you have some explanation that REST API DELETE method is recognised without any problems on windows 10/64bit, but on Ubuntu 16.04 the HTTP server claims "method doesn't exists"? 
The version of bottle is the same 0.12.18

**Comment by agalera** [comment]
@marianlukac Could you provide an example? to be able to test it in multiple environments?

**Comment by defnull** [comment]
Please provide an example that triggers this behavior and re-open the issue.
