### ISSUE TITLE
0.13dev : shutdown of WSGIRefServer

### ISSUE THREAD

**Issue by josephernest** [bottlepy/bottle#1230]
Since 0.13dev [now exposes the server object](https://github.com/josephernest/bottle/blob/master/bottle.py#L3282) in `self.srv` for the `WSGIRefServer`, we could use it for shutdown like this, which is essentially the same than this answer on [StackOverflow](https://stackoverflow.com/questions/11282218/bottle-web-framework-how-to-stop/19749945#19749945):

```
import bottle
@bottle.route('/')
def index():
    return 'hello'
@bottle.route('/stop')
def stopit():
    print('Stopping')
    server.srv.shutdown()
server = bottle.WSGIRefServer(port=80)
bottle.run(server=server)
print('Bye')
```

Opening http://localhost/ works, **but opening http://localhost/stop does not, why?**

**Comment by josephernest** [comment]
I solved it with a new thread:

```
from bottle import WSGIRefServer, run, route
from threading import Thread

@route('/')
def index():
    return 'Hello world'

@route('/stop')
def stopit():
    Thread(target=shutdown).start()

def shutdown():
    server.srv.shutdown()

server = WSGIRefServer(port=80)
run(server=server)
```

**Comment by MartinRamm** [comment]
For anyone else struggling to start the server again after shutting it down: you may need to call `server_close` as well to free up the port and avoid `error: [Errno 98] Address already in use` errors.

Extending from the example above:
```python
def shutdown():
    server.srv.shutdown()
    server.srv.server_close()
```
