### ISSUE TITLE
Your project has been added to a list of copyfree works.

### ISSUE THREAD

**Issue by apotheon** [bottlepy/bottle#1241]
http://copyfree.org/resources/works#Flask

Please let me know if there are any inaccuracies to be corrected or
improvements to be made in the listing.

**Comment by WilliamStam** [comment]
i think you have the wrong project? this is bottle not flask :P or am i mistaken?>

**Comment by apotheon** [comment]
Sorry, I evidently made a copypasta mistake.  It should indeed be: http://copyfree.org/resources/works#Bottle

**Comment by defnull** [comment]
Thanks for the notice
