### ISSUE TITLE
new server adapter

### ISSUE THREAD

**Issue by Ksengine** [bottlepy/bottle#1253]
I like to add new server adapter for [@Ksengine/Servelight](https://github.com/Ksengine/Servelight)
This server is based on wsgiref sourece code.
but with following updates.
- PEP 3333 for python 2
- python 2 and 3 both supported
- unix sockets supported
- Fix for IPv6 addresses
- SSL supported
- threading server - uses threads to handle requests. This is useful to handle web browsers pre-opening sockets, on which Server would wait indefinitely.
- multiprocessing server -handle each request in a new process.
- Prevent reverse DNS lookups
- Prevent ResourceWarning: unclosed socket on KeyboardInterrupt
- when given 0 as port use random port and update port to actual port

**Comment by Ksengine** [comment]
i like to make a PR

**Comment by Ksengine** [comment]
?

**Comment by defnull** [comment]
See #1254
