### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Ksengine** [bottlepy/bottle#1255]
Is this still maintained?
I had created a issue and pr, but no reply

**Comment by oz123** [comment]
First, you made your PR just a few days ago.
Open Source projects are not always paid, and the maintainer might not have the time to review and approve the request promptly.
This project is very selective in the PRs that get approved - hence there are 60 of those open at the time of writing. 
Multiple reasons can be right here. 
I don't want to discourage you - but that's how it is in Open Source. I've seen many PRs of mine get rejected or stale. This can be an opportunity to check if you work on the right stuff, or the quality of the code etc. etc. 
It's also fine to maintain a friendly fork or even completely forking the repository.
What ever you decide, keep in mind that this whole takes time.

**Comment by Ksengine** [comment]
@oz123 Thank You
You had recently starred my server repo
If you have time, please look at my 
- pr #1254
- issue #1253

**Comment by defnull** [comment]
I'm kind of occupied at the moment and focus on actual bug fixes mostly. New server adapters are a special case, as there are a ton of WSGI implementations out there and only limited capacity for support in a micro framework. I'd actually like to phase out server adapters that do not offer a clear and convincing benefit over just hooking everything up the normal WSGI way.

To answer your question: Bottle is maintained, but considered mostly feature-complete. Stability is more important than new features.
