### ISSUE TITLE
Deploying to Cloud Run (Google Cloud Platform)

### ISSUE THREAD

**Issue by imakevirtual** [bottlepy/bottle#1257]
Documentation Link - https://cloud.google.com/run/docs/quickstarts/build-and-deploy#python

The above documentation (Link) mentioned how a Flask app should deploy perfectly to the Cloud Run. But I'm a beginner and I just want to know how to deploy a Bottle app to the Cloud Run.

**Comment by defnull** [comment]
Exactly the same way.

**Comment by imakevirtual** [comment]
Do you mind sharing a sample code of *main.py *please, its a lot for me.
Thank you.

**Comment by defnull** [comment]
This is an issue tracker, not a support forum. Changing the example to work with bottle is really really simple and can be tested locally on your computer. Please try yourself before asking others for help.

**Comment by imakevirtual** [comment]
Thanks, I'll check it out.
