### ISSUE TITLE
No output to console when using external backend server

### ISSUE THREAD

**Issue by mrdc** [bottlepy/bottle#1260]
Hello,

Is it correct behavior that there is no output to console when using, for example, cheroot as backend?

`run(host='0.0.0.0', port=8900, server='cheroot', debug=False)`

I see in console only this:
```
Bottle v0.13-dev server starting up (using CherootServer())...
Listening on http://0.0.0.0:8900/
Hit Ctrl-C to quit.

```

**Comment by Julienh** [comment]
Hello, I have the same issue.

**Comment by defnull** [comment]
Access logs are generated by the server implementation, not by bottle. The wsgiref development server emits logs by default, cheroot does not, apparently. Refer to the cheroot documentation on how to activate access logs.

**Comment by Julienh** [comment]
Not possible I guess : https://github.com/cherrypy/cheroot/issues/89

**Comment by Jwink3101** [comment]
Check out https://stackoverflow.com/a/31093434/3633154

This is what I do

**Comment by rpcope1** [comment]
There's also decent WSGI middleware for doing logging. When using Cheroot with Bottle, I usually use https://pypi.org/project/wsgi-request-logger/ for request logging.
