### ISSUE TITLE
reload not working with bjoern

### ISSUE THREAD

**Issue by cgloeckner** [bottlepy/bottle#1270]
Hi,

I don't know whether it's a bug in bjoern but `reloader=True` seems not to work with `bjoern`.

Example code:
```python
from bottle import route, run

@route('/')
def test():
	return()

run(reloader=True, server='bjoern')
```

I also don't know "what" to report to **jonashaag/bjoern** in order to fix that.

Greetings,
glocke

**Comment by Jwink3101** [comment]
I am not sure what this issue is but I would strongly recommend not using reload in production and only testing other adapters for production.
