### ISSUE TITLE
Fix "DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc'"

### ISSUE THREAD

**Issue by ozooxo** [bottlepy/bottle#1309]
Bottle is currently using `collections.abc` https://github.com/bottlepy/bottle/blob/f9b1849db4dd724e36a93a1032be592193fba581/bottle.py#L125

It is causing this deprecation warning (my warning is from 0.12.17, but the newest (0.12.19) has the same problem):

>   /usr/local/bin/bottle.py:87: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import MutableMapping as DictMixin

Could you please modify it as Python core suggested, so we can get rid of this warning?

**Comment by ricochet1k** [comment]
Please read the error again. eff4960d941b51629f8378b1bd9498ed2aec92c7
