### ISSUE TITLE
global request/response is not coroutine safe

### ISSUE THREAD

**Issue by nu774** [bottlepy/bottle#1330]
Consider example like the following:
```python
@get('/empty')
def empty():
    response.status = 204

@get('/longpoll')
def longpoll():
    response.content_type = 'application/json'
    time.sleep(10)
    return {'value': time.asctime() }
```
When bottle is condifigured to use greenlet based WSGI impl (such as gevent or eventlet) and time.sleep() is monkey-patched, longpoll() _seemingly_ works fine, but it actually does not.

If the app receives a request to <tt>/empty</tt> while waiting in <tt>time.sleep()</tt> in <tt>longpoll()</tt>, <tt>response</tt> is overwritten by the <tt>empty()</tt>. So, long poll returns <tt>204 No Content</tt> instead of the expected JSON response.

In other word, the design of response as global variable is *flawed*, and needs care when used with greenlet.
At least this is documented.

**Comment by oz123** [comment]
Yes it's documented. Where is the issue?

**Comment by nu774** [comment]
Oh, sorry... Then I have missed that one. But where?
I didn't find it in the following:
https://bottlepy.org/docs/dev/api.html#module-contents
https://bottlepy.org/docs/dev/async.html#greenlets-to-the-rescue
https://bottlepy.org/docs/dev/faq.html#common-problems-and-pitfalls

**Comment by defnull** [comment]
The request/response 'globals' are actually _thread local_ and documented as such in several places. By using a greenlet-functions within a request callback, you break some fundamental assumptions about threads without telling bottle about it. You allow multiple concurrent request to be served _in the same thread_, breaking the _thread locality_ of the request and response objects.

It is not enough to just monkey-patch methods you use in your application code, you must also patch thread-related logic in libraries you use. This includes `threading.local` (and be sure to patch that before importing bottle). Both the bottle async primer and the greenlet docs tell you that. The 'gevent' server adapter even goes so far and warns you if you missed that detail.

I agree that the async primer is worded a bit misleadingly and a PR to clear up this misunderstanding would be nice. The example is correct, though.

**Comment by nu774** [comment]
OK, thanks. Closing this issue.
