### ISSUE TITLE
Merge bug fixes into release

### ISSUE THREAD

**Issue by NKID00** [bottlepy/bottle#1332]
#1009 #1188 fixed the date formatting bug in the master branch. However the same bug still exists in the latest release and caused malfunction of my server.

`master`:

 - https://github.com/bottlepy/bottle/blob/f9b1849db4dd724e36a93a1032be592193fba581/bottle.py#L2911-L2912

 - https://github.com/bottlepy/bottle/blob/f9b1849db4dd724e36a93a1032be592193fba581/bottle.py#L2913

 - https://github.com/bottlepy/bottle/blob/f9b1849db4dd724e36a93a1032be592193fba581/bottle.py#L1888

`release-0.12`:

 - https://github.com/bottlepy/bottle/blob/152219818378926f20a5ee3d339118d7cf50a8f6/bottle.py#L2499-L2500

 - https://github.com/bottlepy/bottle/blob/152219818378926f20a5ee3d339118d7cf50a8f6/bottle.py#L2506

 - https://github.com/bottlepy/bottle/blob/152219818378926f20a5ee3d339118d7cf50a8f6/bottle.py#L1648

Is it possible to merge these bug fixes (and also other bug fixes which haven't been merged) into the release branch?

Or should I use the master branch in a production-grade server in order to get the bug fixed?

**Comment by oz123** [comment]
@NKID00 I have been using the master branch for like 4 years now in production.. Never had a problem.
Bottle is quite well tested 💪

**Comment by NKID00** [comment]
@oz123 Thanks. The server using the master branch is working just fine now.

**Comment by defnull** [comment]
This is now fixed in the last stable release (0.13)
