### ISSUE TITLE
Please explain

### ISSUE THREAD

**Issue by valq7711** [bottlepy/bottle#1347]
Hi guys! Could anyone explain the logic behind the following piece of code:
https://github.com/bottlepy/bottle/blob/71bb933649ba009cd537c2e973519d6e024c02a2/bottle.py#L1333-L1339
 As I see `buff[maxread:]` always returns an empty string, since `buff` length cannot be greater than `maxread`, no?

Thanks in advance!

**Comment by defnull** [comment]
Yeah, that part looks strange and can probably be simplified.

```python
while maxread > 0:
    buff = read(min(maxread, bufsize))
    if not buff: raise err
    yield buff
    maxread -= len(buff)
```

**Comment by valq7711** [comment]
Yes, this looks much better ;)

**Comment by Irtiza90** [comment]
Just adding a tiny tiny bit to @defnull's answer
```python
while maxread > 0:
    buff = read(min(maxread, bufsize))
    if not buff: 
        raise err
    # else
    yield buff
    maxread -= len(buff)
```

**Comment by Irtiza90** [comment]
also @valq7711 please close the issue
