### ISSUE TITLE
Is it possible to set multiple cookies in HTTPResponse?

### ISSUE THREAD

**Issue by mrdc** [bottlepy/bottle#1357]
Hello!

I'm trying to set multiple cookies in HTTPResponse and it looks like it's not possible.
This code returns the last cookie (which is expected as it's dict, so keys should be unique):
```python
return HTTPResponse(status = 200, body='abc',headers={'Set-Cookie':'username=Test', 'Set-Cookie':'logged=true'}
```
Manually setting headers in response works fine, but without using HTTPResponse, because it ignores any manually set headers.

```python
response.set_cookie('logged', 'true')
response.add_header('Set-Cookie', 'username=Test')
```

**Comment by avelino** [comment]
```json
headers={'Set-Cookie':'username=Test', 'Set-Cookie':'logged=true'}
```

The declared header is a dictionary [`dict`](https://docs.python.org/3/tutorial/datastructures.html#dictionaries), the behavior of a dictionary is to have unique keys, the way you do this is overwriting the `Set-Cookie` index.

If you use the `response.set_cookie` function to declare multiple cookies
