### ISSUE TITLE
Queue / Batch download and install dependencies?

### ISSUE THREAD

**Issue by bayazidbh** [bottlepy/bottle#1358]
I quite like Bottles' approach compared to normal Wine or even Q4Wine, POL, and CrossOver. However, I play a lot of older Japanese titles, and from my experience they ask for a lot of dependencies.

Having to slowly click one dependency, wait for download and install to finish, then go back and click another one takes too much time and I can't do it while I'm doing something else, however. So would it be possible to download and install dependencies in a queue or batch install of a sort?

For download, I think incorporating it as part of the Preferences like Runners and DXVK would be nice, and would make it easier for people to delete it once they don't need it.

For install, the Bottle creation process and Installers already kinda do this - it would be nice if the buttons aren't grayed out and pressing the next would just queue the operation up. Or alternatively change the button type to a checkbox and then click confirm to just batch install the ones chosen (kinda like with Winetricks).

Would any of that be feasible?

**Comment by Jwink3101** [comment]
This project is a Python web framework. You have the wrong project. Good luck with finding the correct one.

**Comment by bayazidbh** [comment]
Oh my god, I'm so sorry, I just opened the top one in my address bar's suggestion without checking the username (especially since the project also used python and under the name of bottledevs). Please just delete this or something, if that can be done.
