### ISSUE TITLE
Update comment for inclusive language 

### ISSUE THREAD

**Issue by kathytafel** [bottlepy/bottle#1361]
Hi there,

I would like to suggest the updating of bottle.py for inclusive language. It's one small word in one comment here:

https://github.com/bottlepy/bottle/blob/71bb933649ba009cd537c2e973519d6e024c02a2/bottle.py#L1658

At Artsy, we're updating our repositories and dependencies here per this RFC artsy/README#427. For such a change we are adopting 'denylist' over 'blacklist.'

For such a small change I would normally just open a PR, but I want to respect community norms and am new here. 
Thanks. KT

**Comment by biofool** [comment]
This has been sitting her for long enough.  I'm just passing by but I suggest you open the PR.

**Comment by kathytafel** [comment]
Thanks for the nudge @biofool.
