### ISSUE TITLE
Reloader doesn't work with virtualenv .venv

### ISSUE THREAD

**Issue by oijkn** [bottlepy/bottle#1368]
**Issue Summary**
When I activate the run(reloader=True) option from a virtual environment, like `.venv`, the bottle framework doesn't work.

**Environment**
- OS: CentOS 7 & Windows 10
- Python: ^3.6

**To Reproduce**
Code to reproduce the behavior:
```py
run(host="127.0.0.1", port=5000, debug=True, reloader=True)
```

**Expected behavior**
That when we use a virtual environment, the Bottle framework can reload the code when it's modified.

**Error**
`/opt/bootle/.venv/bin/python: can't open file 'main': [Errno 2] No such file or directory`

**Comment by defnull** [comment]
Cannot reproduce. How do you start your script?

**Comment by defnull** [comment]
Closed due to inactivity.
