### ISSUE TITLE
Getting warning on python 3.10.4

### ISSUE THREAD

**Issue by ilya08m1** [bottlepy/bottle#1378]
This is due to some changes in python 3.10 https://docs.python.org/3/library/importlib.html#importlib.abc.MetaPathFinder

![изображение](https://user-images.githubusercontent.com/48233918/171048469-0903de4c-61b0-44f5-badd-72bd542042ea.png)

**Comment by defnull** [comment]
This is triggered by the `bottle.ext` module, which is actually a virtual module with its own loader that allows to import `bottle_whatever` as `bottle.ext.whatever`. Probably best to deprecate this high-magic-low-benefit functionality.
