### ISSUE TITLE
Enhancement: before_first_request

### ISSUE THREAD

**Issue by josephernest** [bottlepy/bottle#1388]
None of the solutions from [Run a function once on bottle.py startup](https://stackoverflow.com/questions/14441884/run-a-function-once-on-bottle-py-startup) are perfect. 

Is there a `before_first_request` (like in Flask) planned for 0.13? (Or maybe another solution is already present in 0.12?)

```
@app.before_first_request
def test():
    print("hello")
```

**Comment by defnull** [comment]
I do not see why you wouldn't simply do that on module level at import time or in some `init_app()` function?

**Comment by josephernest** [comment]
@defnull In some cases, you want to print or do things when and only when the server is really 100% started and ready to take requests.

Example: 

```
@app.before_first_request
def test():
    print("The server is now ready to answer HTTP requests")   # this would not be true if executed before app.run()
```

**Comment by defnull** [comment]
There is no startup phase in Bottle you could wait for. Once the app exists, it is immediately ready to take requests. All preparation work that may be needed happens outside of Bottle. On one side, only the WSGI server implementation knows when the socket is actually bound to a port and the app is reachable. On the other side, only you as an app developer know what needs to happen before the first request (e.g. database migrations) and when your app is ready.

Flask does something different, it intercepts the first arriving request. That is significantly later than "when the server is really" and may even be "never" in some cases. At the same time does not guarantee that other preparation tasks have been completed. I fail to see a use case for such a feature. Do you have an example?

**Comment by josephernest** [comment]
Thank you for your answer.

>  I fail to see a use case for such a feature. Do you have an example?

For now it was just a logging reason. I felt a little bit embarrassed to write

```
custom_log('The server has sucessfully started.')
app.run()  # hey, it only happens *after* this line ;)
```

but maybe later there would be other use cases. I'm maybe overthinking this :)

> only the WSGI server implementation knows when the socket is actually bound to a port and the app is reachable

Is there a way we can do or log something just after the wsgiRefServer has opened the socket/port?

**Comment by valq7711** [comment]
There also may be more than one worker so you will have 'first request' per worker

**Comment by defnull** [comment]
Bottle also 'lies' in its `run()` and prints `Listening to ...` before the server adapter is actually loaded. I think that's forgivable :)

**Comment by josephernest** [comment]
Ok @defnull I will do all my init just the line before I do `app.run()` :) This will be a good `before_first_request ` in probably 99,999% of the cases anyway :)

(Nothing related and out of topic here but just in case the answer is just "yes" or "no": with `SimpleTemplate`, can we combine an `if` with `include`? Example: 

    % if fullpage:
    %     include('header.tpl', title='Page Title') 
)

**Comment by josephernest** [comment]
Here is an example of situation that could require a `before_first_request`:

```
subprocess.Popen(["chrome-win\chrome.exe", "--kiosk", "http://127.0.0.1:5000/"])
app.run(threaded=False, port=5000)
```

In some situations when doing this, `chrome.exe` tries to access http://127.0.0.1:5000/ too early, and the socket is probably not listening yet. This is the only explanation I found to a random bug in which 40% of the time the page is well displayed, and 60% of the time `chrome` displays nothing (?)

**Comment by defnull** [comment]
If yo really need such functionality, you could add a `before_request` hook and immediately remove it again once it is called. 

```py
@app.hook("before_request")
def before_first_request():
    app.remove_hook("before_request", before_first_request)
    # do stuff
```

This would have semantics similar to Flasks `before_first_request` hook (which I still find strange).

**Comment by defnull** [comment]
Fun fact: `before_first_request` is deprecated in Flask too, for the same reasons I never introduced it.

**Comment by josephernest** [comment]
Thanks @defnull! Oh good to know it's deprecated also for Flask. 
You're right: I don't need it. I thought I needed to wait for the server to be ready to take requests before launching `chrome.exe http://127.0.0.1/`, but in fact the problem I was encountering was somewhere else: https://github.com/bottlepy/bottle/issues/1389. Solved!
