### ISSUE TITLE
Add devices toggle to dedicated sandbox

### ISSUE THREAD

**Issue by Froggy232** [bottlepy/bottle#1391]
Hi,
The dedicated sandbox let setting network and sound permission per bottle, but not devices.
It should allow that in order to let sandboxed games use the controller.
Thanks you
![Capture d’écran du 2022-08-16 18-23-37](https://user-images.githubusercontent.com/72796064/184930201-d1de2fbc-a90a-4fb1-805d-e169f176b229.png)

**Comment by cryzed** [comment]
This isn't the [Bottles](https://usebottles.com) project, it's [Bottle](https://bottlepy.org/docs/dev/).

**Comment by defnull** [comment]
Yes, wrong project :)
