### ISSUE TITLE
Using JavaScript MQTT over websockets client within Bottle

### ISSUE THREAD

**Issue by alan-rpi** [bottlepy/bottle#1404]
First, many thanks to the developers for creating Bottle. I've found it easy to use. 

Is there an active forum where I can ask for ideas? I wondering if it would be possible to add user code to subscribe to MQTT and receive messages so it can display data in real time? Maybe a template could use javascript? A search has found JavaScript MQTT over websockets client.

Alan

**Comment by defnull** [comment]
Websockets do not mix well with the one-thread-per-request model of WSGI. There are ways around it though, as documented here: https://bottlepy.org/docs/dev/async.html#finally-websockets
