### ISSUE TITLE
Standard way to get UTF8 query parameters

### ISSUE THREAD

**Issue by josephernest** [bottlepy/bottle#1408]
When launching this:

```
import bottle, random, time
from bottle import request
app = bottle.Bottle()
@bottle.route('/')
def index():
    r = request.query["a"]
    print(r)
    return ''
bottle.run(port=80)
```

and calling http://127.0.0.1/?a=test%C3%A9 gives:

    testÃ©

What is the standard way to get `testé` instead?

I already read https://github.com/bottlepy/bottle/issues/1085 but I wondered what should be the "standard way". Would it be `request.query.decode()["a"]`? (If so, why is an extra decode necessary here?)

**Comment by defnull** [comment]
Query parameters do not have an encoding. We can _assume_ it is `utf-8` nowadays, but there is no guarantee at all. For Python2, `request.query["a"]` returned the raw byte string and `request.query.a` a decoded unicode string. With python3, those raw strings are also unicode, but decoded with `latin1`, a reversible encoding. That's part of the WSGI spec. Attribute access (e.g. `request.query.a`) is still the preferred way to get a single properly decoded value. Or `request.query.decode()` to convert all parameters at once. https://bottlepy.org/docs/dev/tutorial.html#introducing-formsdict

**Comment by asashnov** [comment]
Worked for me.
Replacing 
```
    filename = request.params.get('filename')
    return static_file(filename)
```
to
```
    filename = request.params.filename
    return static_file(filename)
```
fixed the downloading of UTF-8 filename.

**Comment by josephernest** [comment]
@defnull About query parameters, I see `request.query` has a special type `bottle.FormsDict`.
What is the benefit of using this over a standard dict? (Out of curiosity, in the history of Bottle development, what made you switch to a specific type?)
Can I safely convert it to a `dict`? For example, when, inside a route function, we need to call another function with all the query parameters. Or are there cases in which we shouldn't convert `request.query.decode()` to a `dict`?

Thanks again for your great lib!

**Comment by josephernest** [comment]
Thanks @Marrin. I now see https://bottlepy.org/docs/dev/api.html#bottle.MultiDict.
For a request query, in which case is it needed to have multiple values per key? I don't see a use case example.

**Comment by defnull** [comment]
Both queries and forms can have multiple values per key, for example `?foo=bar&foo=baz`. Think about a multi-select element in an HTML form. `FormsDict` is a `MultiDict` so you can access all values if needed, but it still behaves like a normal single-value dict if you do not care about multiple values. It then just returns the last value per key.

The other reason for `FormsDict` is already explained above (text vs. unicode). You can 'fix' all the encoding issues in one go with `FormsDict.decode()`. That returns a new `FormsDict` but with everything already re-encoded properly. It behaves like a normal dict, so you can just pass that to any libraries that expect dicts. Or you can make a copy (e.g. `copy = dict(request.query.decode())`).

**Comment by josephernest** [comment]
Thanks @defnull! Oh I thought `?foo=bar&foo=baz` was always equivalent to `?foo=baz` (the latest only is kept if multiple definitions) in the HTTP URL schemes specifications, but now I discover it's not!

(I don't remember where it is defined "officially", maybe something like https://www.ietf.org/rfc/rfc1808.txt but I couldn't find)
