### ISSUE TITLE
The Deployment section of the docs

### ISSUE THREAD

**Issue by arjunsatarkar** [bottlepy/bottle#1409]
[Deployment](https://bottlepy.org/docs/stable/deployment.html) lists many server backends. Here are some which seem defunct and thus IMO not really suited to running a production web server.

flup - website down.
cherrypy - site replaced with some SEO spam blog?
paste - site parked/redirects to some ads.
rocket - last commit 2017, almost 6 years ago.
diesel - site blank, or possibly ad-ridden, I'm not sure since I block ads.
fapws3 - last commit 2017, almost 6 years ago.
meinheld - site is now an SEO spam blog, last commit 2020.

I realise the code might work, but given that the web tends to change, I would not be surprised if some part of these were to suddenly break in the future (or already have). Plus, there is not going to be any hope of reporting any extant issues - including security issues. So it is probably best to remove them.

Also, a minor note - eventlet's site supports HTTPS but does not redirect HTTP to HTTPS. Bottle docs links to the HTTP version. It would be better if they linked to the HTTPS version.

Anyway, that decimates the entire multi-threaded section except Waitress. So I have a question about the asynchronous ones. The docs say they "can get a bit tricky" and you "need to design your application accordingly", but it's hard to find resources regarding what one needs to do to use, say, tornado effectively with bottle. It would be nice if the docs said something more specific about this.

**Comment by premins** [comment]
CherryPy should be https://cherrypy.dev/

**Comment by valq7711** [comment]
- gunicorn is also multi-threaded, as for me - `the best of` for production (with nginx of course)
- rocket for python3 - https://github.com/web2py/rocket3
- tornado **can** run wsgi app, but it is absolutely not intended for this (see warning https://www.tornadoweb.org/en/stable/wsgi.html)

"can get a bit tricky" - I think this is a general remark about any asynchronous code.
WSGI is not async by its nature, there is only one easy way to make WSGI app to work as async-like - use gevent with monkey patching (it is a bit hacky).
If you really need async app - you'd better look at FastAPI

**Comment by defnull** [comment]
Documentation now recommends gunicorn and cheroot and most broken links should be fixed.
