### ISSUE TITLE
0.12.24: test_server: 'fetch' method may unintentionally use system proxy

### ISSUE THREAD

**Issue by jayaddison** [bottlepy/bottle#1410]
The `test_server` test module performs a bunch of webserver self-tests against `localhost` (127.0.0.1), and includes a [`fetch` method definition](https://github.com/bottlepy/bottle/blob/e2404c311fca55ae5058b714db2349aa8eb1e6bd/test/test_server.py#L79-L83) to support that.

The (probably sensible) [defaults for `urlopen`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen) will use a proxy if one is configured in the environment:

> In addition, if proxy settings are detected (for example, when a `*_proxy` environment variable like `http_proxy` is set), [`ProxyHandler`](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler) is default installed and makes sure the requests are handled through the proxy.

...but since we're making a request to `localhost` as part of a unit test, we probably don't want the potential for remote network services to be involved (since they could affect test performance and results).  Fortunately we can disable them by using [`ProxyHandler.__init__` arguments](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler):

> To disable autodetected proxy pass an empty dictionary.

(and even better, for backwards-compatibility in this library: the [same parameter is available in Python 2.7's `urllib2.ProxyHandler`](https://docs.python.org/2.7/library/urllib2.html#urllib2.ProxyHandler))

**Comment by defnull** [comment]
Easiest workaround would be to add `os.environ["NO_PROXY"] = "*"` for the duration of tests.

**Comment by jayaddison** [comment]
> Easiest workaround would be to add `os.environ["NO_PROXY"] = "*"` for the duration of tests.

True, that could work.  Are we sure that none of the webserver implementations that are tested make any outbound requests during import/initialization?

**Comment by defnull** [comment]
Fixed in 0.12.15
