### ISSUE TITLE
Save the chat results to the database

### ISSUE THREAD

**Issue by wnesbv** [bottlepy/bottle#1415]
python 3.11
`

    def save_msg(story):
        user_list = "who_is_who()[0]"
        generated = datetime.now()
    
        cur = con.cursor()
        data = (story, generated, user_list)
        cur.execute(
            "INSERT INTO chat_table (story, generated, user_list)VALUES (?,?,?)",
            data,
        )
        con.commit()
        cur.close()
    
        return data
`
`

    def communicate(self, client, payload, isBinary):
        for i, c in enumerate(self.clients):
            if c["client"] == client:
                id = i
                break
        for c in self.clients:
            data = "Client {0}: {1}".format(str(id + 1), payload.decode("utf-8"))
            c["client"].sendMessage(str.encode(data))

            print("msg..!.!.!", data)
            save_msg(data)

`
# ..
It all comes down to ("who_is_who()[0]")
jwt token:
`
{
  "id": 2,
  "name": "Second user name",
  "mail": "two@gmail.com"
}
`
# ..
          File "E:\autobahn_python\chat\urls.py", line 71, in onMessage
            self.factory.communicate(self, payload, isBinary)
          File "E:\autobahn_python\chat\urls.py", line 98, in communicate
            save_msg(data)
          File "E:\autobahn_python\chat\urls.py", line 43, in save_msg
            user_list = who_is_who()[0]
          File "E:\autobahn_python\env\Lib\site-packages\bottle.py", line 1553, in __getitem__
            def __getitem__(self, name):  return self._headers[_hkey(name)][-1]
          File "E:\autobahn_python\env\Lib\site-packages\bottle.py", line 1419, in _hkey
            if '\n' in key or '\r' in key or '\0' in key:
        builtins.TypeError: argument of type 'int' is not iterable

2023-03-14 10:25:40+0300 [-] Client disconnected: tcp4:127.0.0.1:50236

**Comment by defnull** [comment]
Your `who_is_who()` function seems to return a `bottle.HeaderDict` instance and not what you probably expect. Header names are strings, not integers (`0` in your example).

**Comment by defnull** [comment]
Your `who_is_who()` returns `bottle.HTTPError` in some cases, which explains why `who_is_who()[0]` triggers the error you are seeing. Did you mean to `raise HTTPError(...)` instead of returning it? Anyway, this is not a Bottle bug, please do not use this issue tracker to ask for help with your own application.
