### ISSUE TITLE
pyright gives "Object of type ModuleType is not callable" with OO way for route

### ISSUE THREAD

**Issue by ilrico** [bottlepy/bottle#1417]
Hello,
I have a new error from pyright (maybe new release of pyright or bottle 0.12.25)
```
from bottle import Bottle

app = Bottle()

@app.route('/my/path', 'GET'):     # Object of type ModuleType is not callable
def my_path_function():
    ...
```

with the default_app method, I have no error:
```
from bottle import route

@route('/my/path', 'GET'):
def my_path_function():
    ...
```

For various reasons, I'd like to stick to OO way.
Anyone experiences same issue ? Any clue how to solve ?

**Comment by defnull** [comment]
Decorators do not end with a colon. That's a syntax error. Remove the `:`.

That said: Bottle lacks proper support for pyright at the moment because it needs to support very old python versions, so you will get a lot of warnings even if everything is correct.

**Comment by ilrico** [comment]
Sorry, it's a typo in my question, no colon in my code.
Regarding a thread on pyright issue tracker, seem it's a consequence of dynamic import at runtime (static checkers cannot deal with it... I forced py = (3, 11, 0) without improvement.

**Comment by defnull** [comment]
There is nothing special about `Bottle.route()`. It's a normal method of the `Bottle` class, the `ModuleType is not callable` error does not make sense in that context.

**Comment by ilrico** [comment]
I totally agree with that.
Quick and very dirty fix, I commented, in Bottle.route()
`# if isinstance(callback, basestring): callback = load(callback), `
since I never use callbacks in route

(not directly related, for those using static linter, also add hints method: str | list[str] = 'GET' in route() signature, usefull when you need method=['options', 'post'] )
