### ISSUE TITLE
Please backport "Fix #1378: Module loader should move from find_mdoule to find_spec." to 0.12.x

### ISSUE THREAD

**Issue by mgorny** [bottlepy/bottle#1422]
Could you please backport ca6762c559c5e71e0dff71dc97eb4c6b3ed9bbcd to 0.12.x? It fixes compatibility with Python 3.12.0b1.

```
commit ca6762c559c5e71e0dff71dc97eb4c6b3ed9bbcd
Author: Marcel Hellkamp <marc@gsites.de>
Date:   Sun Jun 12 15:15:35 2022 +0200

    Fix #1378: Module loader should move from find_mdoule to find_spec.

 bottle.py | 9 +++++++--
 1 file changed, 7 insertions(+), 2 deletions(-)
```

**Comment by defnull** [comment]
Python 3.12 should work as expected, do you mean the upcoming Python 3.13 perhaps? Bottle 0.12 won't support Python 3.13 because they removed `cgi.FieldStorage` for multipart parsing. This is why Bottle 0.13 was releases just recently. Is there a reason you cannot upgrade to Bottle 0.13?

**Comment by mgorny** [comment]
Given that this bug is 1.5yr old, I don't really recall what was the actual issue here (it might have been something that changed post-beta). Anyway, with 0.13.x is out, I don't think there's a need to do anything.
