### ISSUE TITLE
bottlepy.org is down?

### ISSUE THREAD

**Issue by rmarsh1126** [bottlepy/bottle#1433]
I've been trying to access the documentation for this framework on your linked website. However I get a connection refused error. Is this a temporary issue or are you switching to a different homepage?

**Comment by defnull** [comment]
Thanks for the notice. The nginx process stopped for unknown reasons (nothing special in logs). Probably a letsencrypt issue. It works again.

**Comment by rmarsh1126** [comment]
Fantastic! Thanks for the rapid response!
