### ISSUE TITLE
python windows service script fails to run when you import bottle

### ISSUE THREAD

**Issue by smanross** [bottlepy/bottle#1434]
I am somewhat new to bottle, and was testing with an ipython/console bottle app for a while (which worked well) and in the process to convert the console app to a windows service python script, I ran into an issue with some basic python service code that just sits around waiting for a stop/start request (which was working).  JUST adding the "import bottle" command to the working service script caused the working service script to fail.

I tracked the issue down to this code:
```
# Workaround for the "print is a keyword/function" Python 2/3 dilemma
# and a fallback for mod_wsgi (resticts stdout/err attribute access)
try:
    _stdout, _stderr = sys.stdout.write, sys.stderr.write
except IOError:
    _stdout = lambda x: sys.stdout.write(x)
    _stderr = lambda x: sys.stderr.write(x)
```

This makes sense because windows services typically don't handle stdout/stderr output well.

In my case, I'm not using **mod_wsgi**, so I just commented that code for now and the service code started working again.  **Do you see any issues with that resolution (in my specific case)?**

As well, would **mod_wsgi** only be used in a *nix environment or is that a workable solution in M$ environments as well since we would be able to exclude this code only on an M$ environment?

Lastly, I'm not pushing for a fix for this, but wanted this information visible to anyone else who is trying to do the same thing and running into issues.

Thanks for your great python contributions and documentation!

**Comment by defnull** [comment]
> This makes sense because windows services typically don't handle stdout/stderr output well.

"Under some conditions `stdin`, `stdout` and `stderr` [...] can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with `pythonw.exe`." https://docs.python.org/3/library/sys.html#sys.__stdout__

You can fix that by running the script with `python.exe` instead of `pythonw.exe` (not sure how that works with services, I do not use Windows), or by monkey-patching both before you import bottle:

```py
import sys, os
sys.stdout = open(os.devnull, 'a+', buffering=1)
sys.stderr = open(os.devnull, 'a+', buffering=1)
import bottle
```

**Comment by smanross** [comment]
I will test that!!!  Thanks!
