### ISSUE TITLE
Is it possible to change "Bottle v0.12.25 server starting up..." when run script?

### ISSUE THREAD

**Issue by rikhtehgaran** [bottlepy/bottle#1445]
Hi, can we override the text when we start our script? without the need to change the source in the virtual environment 
![image](https://github.com/bottlepy/bottle/assets/3824913/76d79cf6-26a5-4540-b02c-03f320c3a1d3)

**Comment by FriedrichFroebel** [comment]
No, unless you monkey-patch the `_stderr` function and filter the messages according to your needs.

**Comment by defnull** [comment]
You can disable the messages (by running `bottle.py --quiet ...` or calling `bottle.run(quiet=True, ...)`) and then print your own message.

**Comment by defnull** [comment]
Oh, there is no `bottle.py --quiet` parameter, I could have sworn... but the `bottle.run(quiet=True, ...)` way still works.
