### ISSUE TITLE
Syntax check for SimpleTemplate Engine

### ISSUE THREAD

**Issue by FreeAndFrei** [bottlepy/bottle#1447]
Hi, friends.
Do you think it's possible to make some kind of syntax check for the templates in some IDEs like PyCharm?
I, personally have no experience in developing that, but I think it's possible.

**Comment by defnull** [comment]
Support for additional formats would have to be implemented as IDE plugins or by extending the parser frameworks used by those IDEs. You could open an issue with the PyCharm folks and test your luck.
