### ISSUE TITLE
Broken WSGI Environment link on documentation

### ISSUE THREAD

**Issue by quazi-irfan** [bottlepy/bottle#1448]
Broken link in the document: https://bottlepy.org/docs/dev/WSGI_Specification

Found at Section 1.1.5:
WSGI ENVIRONMENT[¶](https://bottlepy.org/docs/dev/tutorial.html#wsgi-environment)
...
Most of the interesting data is exposed through special methods or attributes, but if you want to access [WSGI environ variables](https://bottlepy.org/docs/dev/WSGI_Specification) directly, you can do so:

**Comment by defnull** [comment]
Fixed in 02137987220dd9b311b2c589afc2d097c66bacb1, thanks
