### ISSUE TITLE
test data ? needs updating in 0.10.9.

### ISSUE THREAD

**Issue by idella** [bottlepy/bottle#323]
1) ZeroDivisionError is absent from the file tested read and tested in test/test_outputfilter.py
2) ''' The virtual module needs a valid **file** attribute.
   If not, the Google app engine development server crashes on windows.'''
 A Windows issue it seems in test/test_importhook.py
These two tests possibly need a fix.  There was one other but that is a gentoo sandbox issue that isn't an error.

```
    sed -e 's:ZeroDivisionError:Internal Server Error:g' -i test/test_outputfilter.py || return
    sed -e "s/        self.assertTrue/#        self.assertTrue/" -i test/test_importhook.py || return
```

in the ebuild sees these succeed.

**Comment by aames** [comment]
Hi @idella 

Are these still issues?

If so, could you provide specific steps to reproduce and any environment details you think may be relevant and I'd be happy to take a look.

Thanks in advance 😄
