### ISSUE TITLE
Forms use wrong encoding

### ISSUE THREAD

**Issue by ritave** [bottlepy/bottle#353]
When using letters such as "ą", "ł" in forms on Chrome, Mac OS X, I get wrongly encoded string back on the server. Respectively "Ä" (note there are 2 chars there, 1 invisible), and "Å".

**Comment by vgoffman** [comment]
> Ahh ok. Thats a Python 3 nastiness. See http://bottlepy.org/docs/dev/tutorial.html#unicode-issues

I have same issue but this link is not exist anymore. can you please share correct code for this issue? thanks

**Comment by defnull** [comment]
It's still described here: http://bottlepy.org/docs/dev/tutorial.html#introducing-formsdict (the big yellow box) and in the docstrings of the FormsDict itself.

In short: Item access (e.g. request.forms['foo']) will return whatever the WSGI webserver provides, which is a byte string in Python2 and an latin-1 decoded unicode string in python 3. To get the properly utf8 decoded value, use attribute access (e.g. request.forms.foo) or request.forms.getunicode('foo').
