### ISSUE TITLE
Handling the OPTIONS method

### ISSUE THREAD

**Issue by ghost** [bottlepy/bottle#402]
My app needs to handle cross-domain requests. This means that I need to handle the OPTIONS method, because the browser will send OPTIONS <path> before GET <path>. Handling this is not very convenient in Bottle, because I need to double the number of the routes. The other way to do it would be the catch-all route:

    @bottle.route('/<:re:.*>', method='OPTIONS')

but this won't of course work - depending on the order of definitions, either the OPTIONS will not work, either the GET.

Currently, all my OPTIONS handlers do the same thing, so a single function is enough. Is there a way to handle this nicely? If not, then I think this case is specific enough to make an exception in the routing mechanism.

**Comment by brentpayne** [comment]
Is there a new workaround?

**Comment by paulocheque** [comment]
Any news about this?

@ghost I use your solution `@bottle.route('/<:re:.*>', method='OPTIONS')` and it is working for me for a while using the 0.13 version.

**Comment by andy250** [comment]
Any updates on the workaround?

**Comment by defnull** [comment]
It is no longer needed. The router matches the method first, the path later. ``route ('<any:path>', 'OPTIONS')`` no longer shadows more specific GET routes.

**Comment by andy250** [comment]
Nice, thanks!

**Comment by lupasebastian** [comment]
> Just a quick workaround::
> 
> ```
> @bottle.error(405)
> def method_not_allowed(res):
>     if request.method == 'OPTIONS':
>         new_res = bottle.HTTPResponse()
>         new_res.set_header('Access-Control-Allow-Origin', '*')
>         return new_res
>     res.headers['Allow'] += ', OPTIONS'
>     return request.app.default_error_handler(res)
> 
> @bottle.hook('after_request')
> def enableCORSAfterRequestHook():
>     bottle.response.set_header('Access-Control-Allow-Origin', '*')
> ```

logged in specifically to give a heart, saved me lots of hassle. thanks!

**Comment by Noob7** [comment]
guys iv tried everything, in some cases preflight lands on my method successfully send origin header but still post fails. This shouldn't be this hard honestly in express and node its about 50 times simpler :(

**Comment by Noob7** [comment]
also what do we do when its options just return?
if request.method=='OPTIONS':
       return
