### ISSUE TITLE
Bottle no longer running with Jython

### ISSUE THREAD

**Issue by alex3627** [bottlepy/bottle#460]
Bottle was running with version 0.11, the current development version "'0.12-dev" seem to drop jython support.

  File "/path/to/bottle/bottle.py", line 1989, in <module>
    class _iterchain(itertools.chain):
TypeError: Error when calling the metaclass bases
    reflectedfunction(): expected 1 args; got 3

**Comment by jimbaker** [comment]
For Jython 2.7.1, we fixed an underlying Jython bug in our regex implementation, namely lack of support for zero-width matches. So @defnull, that was a correct hypothesis, although it took us some time to find the specific problem! So now Jython supports SimpleTemplate processing. See https://hg.python.org/jython/rev/636b124a7587 for the specific change set.

I didn't look at all servers in the test suite (which are the remaining errors), and I know some are not supported on Jython like eventlet (possibly never will support eventlet), but servers like CherryPy run without problem. But for Jython, usually Bottle apps should run in the context of a WSGI/servlet bridge like Fireside or ModJy, which should just work now.

**Comment by defnull** [comment]
Thanks for the follow up :)
