### ISSUE TITLE
Allowed to use route config in this way?

### ISSUE THREAD

**Issue by bulv1ne** [bottlepy/bottle#479]
I was wondering if this is a legal way of using the **config parameter in route? The functionality is very similar for the 4 routes, that's why I'd like to use only one function.

```python
@app.route('/inc', ajax=False, amount=1)
@app.route('/dec', ajax=False, amount=-1)
@app.route('/ajax/inc', ajax=True, amount=1)
@app.route('/ajax/dec', ajax=True, amount=-1)
def incdec():
    ajax = request['bottle.route'].config['ajax']
    amount = request['bottle.route'].config['amount']
    ...
```

**Comment by defnull** [comment]
This finally works in the last commit:

    request.route.config # contains route AND app config parameters
    request.app.config # contains only app config.
