### ISSUE TITLE
If %include and %rebase are to be functions...

### ISSUE THREAD

**Issue by rcarmo** [bottlepy/bottle#522]
...what is the correct way to do:

```
cat layout.tpl
<h1>{{title}}</h1>
<div id="main" class="ink-grid">
        %include
</div>

cat variant.tpl
{{!data}}
%rebase('layout', title=title)
```

I keep getting a DeprecationWarning on that %include, and the docs for 0.12-dev aren't updated with the proper syntax.

**Comment by zcattacz** [comment]
I %rebase("templatename") supposed to work inside an template file ?
with the latest stable bottle, %rebase("template") works in """ """ quoted strings in py, but when I put the in side a template file, and reference the template in a template call, it doesn't work, "%rebase...." is printed directly in the rendered webpage.
Any idea ?

**Comment by defnull** [comment]
Make sure there is nothing in front of the ``%``

**Comment by zcattacz** [comment]
Still have the problem. 
Until I converted my template encoding from UTF8 to UTF8 wihtout BOM.
By "nothing in front of the %" You are still right though ...

**Comment by defnull** [comment]
Is BOM a windows thing? I never understood why it is needed for UTF-8 (which is immune to byte order problems) and why it does not count as white-space in regular expressions in some cases.
