### ISSUE TITLE
Mounted app and get_url()

### ISSUE THREAD

**Issue by damiencorpataux** [bottlepy/bottle#556]
### Problem

`get_url()` doesn't take the prefix of mounted applications into account:

Mounting `bar` into `foo` gives no way to _get the urls of the mounted app_ using `get_url()`:
- `app.get_url('/bar')`: RouteBuildError: ('No route with that name.', '/bar')<br>
  **rationale:** the _bar app_ urls are unknown to the _foo app_
- `bar.app.get_url('/bar')` /bar<br>
  **rationale:** the _bar app_ doesn't know it was mounted into _foo app_
### Example

**foo.py (root app):**

``` python
import bottle
import bar

app = bottle.default_app()

@app.route("/")
def index():
    return "hello foo"

import bar
app.mount("/bar", bar.app)

if __name__ == "__main__":
    bottle.run(host="localhost", port=8080, reloader=True)
```

**bar.py (mounted app):**

```
import bottle

app = bottle.Bottle()

@app.route("/")
def index():
    return "hello bar"
```

Anybody got something on this issue?

**Comment by karelv** [comment]
+1

**Comment by karelv** [comment]
I used a variant on your 'hack' solution:

```py
for route in api.app.routes:
    r = copy(route)
    r.rule = '/api'+r.rule
    if (r.name != None):      
      r.name = 'api.'+r.name
    app.add_route(r)
```
And in `app.py` I can use the named routes from `api` as `app.get_url ('api.named_route')`

**Comment by avelino** [comment]
@damiencorpataux @karelv 
An solution[1] pretty how to do!

The way I see it is easier to understand what happens using the API (bottle) mount:

    app.mount('/api', api_app)

to 

    api_app.get_url('/api')

Even using the `get_url` (purpose), you would have to use the `add_route`, more work than using `app.mount`.

[1] https://github.com/avelino/mining/blob/master/manage.py#L41:L43

**Comment by eric-wieser** [comment]
@avelino, I can't extract any meaning from your post at all...
