### ISSUE TITLE
Windows Style line break causes Syntax Error

### ISSUE THREAD

**Issue by vhpanisa** [bottlepy/bottle#643]
%>\n  in Windows breaks bottle

**Comment by syegulalp** [comment]
For others who might have run into this: I was able to solve this problem by simply saving my templates with Unix-style line breaks.

**Comment by eric-wieser** [comment]
This was fixed in 40fa1ca66efeb5c946a9a1fa470da3359c025701, which sadly hasn't made it to PyPI

**Comment by vhpanisa** [comment]
Fixed in 40fa1ca
