### ISSUE TITLE
Request with invalid JSON throws a 500

### ISSUE THREAD

**Issue by jrobn** [bottlepy/bottle#654]
Currently, when a request with invalid JSON is sent to the server it causes a `JSONDecodeError` to be thrown by the underlying parser (simplejson in this case).

Bottle should catch and re-throw a 400 Bad Request `HTTPError` to indicated the the client that something is wrong with the request.

**Comment by egonzalez777** [comment]
Hello bottle team, do we know why this change is not available in the 0.12.9 release code?

We upraded our bottle application to 0.12.9 with the notion that this item was added, but when we checked, this code update was not part of the code released.

Thanks
