### ISSUE TITLE
`after_request` won't reflect the out going response on error

### ISSUE THREAD

**Issue by grissiom** [bottlepy/bottle#671]
Simple test code:

``` .Python
import bottle as bt

@bt.hook('after_request')
def log_request_a():
    print 'resp to: %s, %s' % (bt.request.remote_addr,
                                       bt.response.status_line)

@bt.get('/')
def _get():
    print 'return 400'
    bt.abort(400, 'test')

bt.run(server='cherrypy', host='localhost',  port=1888)
```

It will always print `resp to: 127.0.0.1, 200 OK` , not 400.

**Comment by stessaris** [comment]
Why the changes to fix this issue had been rolled back? In the current version of the code  `after_request` hooks don't receive the error, so the problem is still there.

Is there another way to get hold of the error?
