### ISSUE TITLE
Nested Bottle app with Waitress

### ISSUE THREAD

**Issue by PlaidPhantom** [bottlepy/bottle#678]
I am building a web application using nested Bottle apps and I'm having problems returning a static file from the nested app when running the site through the Waitress web server.  It works fine when run with WSGIRefServer.

Sample app that replicates the issue below (browse to `/test/`).  If I run the app using WSGIRefServer (commented run command) then the javascript file downloads fine.  If i use `server="waitress"` then /test/js returns a blank response (no errors).

```python
from bottle import Bottle, run, static_file

baseapp = Bottle()
app = Bottle()
baseapp.mount("/test/", app)

@app.get("/")
def index():
    return """<!DOCTYPE html>
<html><body>
<p>Result: <span id="asdf">Failed :(</span></p>
<script src="js"></script>
</body></html>
"""

@app.get("/js")
def js():
    return static_file("test.js", "./")

run(app = baseapp, server="waitress", url="0.0.0.0", port=8080)
#run(app = baseapp, url="0.0.0.0", port=8080)
```
    
Contents of test.js:

```javascript
document.getElementById('asdf').innerHTML = 'Worked! :)';
```

I'm running Python 3.4.2 with Bottle 0.12.7 and Waitress 0.8.9. (downloaded via pip).

**Comment by PlaidPhantom** [comment]
Just to ping this, I am still having this issue after upgrading to bottle 0.12.8.

**Comment by defnull** [comment]
> Why should bottle check whether or not body is True or False? Should it simple check it is an iterable object?

WSGI applications must always return an iterable. I think this logic would fix the issue:

    rs.body = itertools.chain(rs.body, body) if rs.body else body

We lose support for WSGI apps returning ``None`` or ``False`` or other non-true non-iterators, but that is not allowed in WSGI anyway.

But I still think that waitress is at fault here. A non-empty iterator should not evaluate to ``False`` just because it does not know if it is empty or not.

**Comment by djamelfel** [comment]
I have got the same issue when I try to mount a plugin on my web application: 
`WARNING:waitress:application returned too few bytes (0) for specified Content-Length (1142) via app_iter`

Do you know how I can work around this issue until this is fixed upstream?

**Comment by frankdarcy** [comment]
Workaround ...
In the bottle app, if I remove  'wsgi.file_wrapper' from request.environ then it all works fine.
Like so ..
```
@app.get("/js")
def js():
    if 'wsgi.file_wrapper' in request.environ:
        del request.environ['wsgi.file_wrapper']
    return static_file("test.js", "./")
```

**Comment by defnull** [comment]
This is now an open bug in waitress. I'll close this here for now.
