### ISSUE TITLE
Mishandling JSON data in Python3, but not Python2

### ISSUE THREAD

**Issue by abingham** [bottlepy/bottle#698]
I've got a bottle-based HTTP server that mostly shuffles JSON data around. When I run this in Python 2.7 it works perfectly, and in my route handlers I can access the JSON data via bottle.request.json. However, when I run it under Python 3.4 bottle.json.request is None.

I've examined the HTTP traffic, and in both cases it is exactly the same (as would expected since that's under control of the non-Python-dependent client.)

I also see that the JSON data is reaching bottle in both cases. If I print out bottle.request.params.keys(), I see the string-ified JSON as the only entry in the list in both cases. And the strings are identical in both cases. For some reason, however, the Python 2 version is recognizing the JSON data while the Python 3 version isn't.

Strangely, this used to work, but some recent change either in my code or bottle (or both) has broken things. Looking over my code, though, I can't see what I might have done to create the problem, so I can only assume it's a problem with bottle and/or its interaction with Python3.

**Comment by abingham** [comment]
FWIW, I also [posted this question to stackoverflow](http://stackoverflow.com/questions/27479519/bottle-mishandling-json-data-in-python3-but-not-python2).

**Comment by defnull** [comment]
You are shipping an old version of bottle in your git repository. Please verify with a up to date copy.

**Comment by abingham** [comment]
I think I tested with a more recent bottle.py when I first ran into this issue, but I might be mistaken. Should I try the version in `master`?

**Comment by eric-wieser** [comment]
Either that or the one on PyPI, yes

**Comment by abingham** [comment]
I've tested against `master` and get the same result. 

Actually I'm running against a [patched version of `master`](https://github.com/abingham/bottle/commits/multi_phase).

This patch adds support for a multi-phase server initialization that allows me to print server's actual port before running it. I need this patch because otherwise I can't know which port was selected for the server. I've had this patch open as a [pull-request for some time](https://github.com/bottlepy/bottle/pull/571). That PR is out of date now, but my `multi_phase` branch brings it up to date with `master`.

It's entirely possible that my patch has introduced the bug, so let me know if that appears to be the case.

**Comment by defnull** [comment]
The ``request.json`` method does not do much other than checking the content-type and parsing the request body with ``json.loads()`` from the standard library. Could you provide a minimal example that does not work?

**Comment by abingham** [comment]
I'll see what I can do.

**Comment by defnull** [comment]
I'm asking because I cannot reproduce your error with the following example:

  $ cat json_test.py 
  import bottle
  @bottle.post('/')
  def test():
      print(bottle.request.json)
      return 'OK'

  $ PYTHONPATH=/home/marc/coding/bottle/  python3.4 -mbottle json_test

  $ curl -H "Content-Type: application/json" --data '{"foo":"bar"}' http://localhost:8080/

**Comment by abingham** [comment]
Right, I'll try to replicate something along those lines as well.

**Comment by abingham** [comment]
OK, after a good amount of digging it appears that the problem does not lie in bottle. My guess is that some behavior in `wsgiref` changed, and that's why I'm seeing the problem. It looks like part of the emacs-lisp http stack is tacking a `Content-Type: x-www-form-urlencoded` onto my request along with the json one, and different headers are ultimately reported to bottle in different Python version.

At least, that's my hypothesis right now. It looks like the bug is in the emacs stack (surprise surprise!), so I think it's safe to close this issue. Thanks for your help, and sorry for the distraction.

**Comment by defnull** [comment]
Okay, thanks for the feedback :)
