### ISSUE TITLE
static_file behaves incorrectly when serving different files from the same URL, due to incorrect caching

### ISSUE THREAD

**Issue by TomTervoort** [bottlepy/bottle#718]
I recently encountered a strange issue where my browser was returned a `304 Not Modified` response by my Bottle app, even though the content it was fetching most defininately was modified. It turns out this was caused by a problem in `static_file`:
### The problem

Given a router that looks like this:

```
@get('/some-url')
def someFile():
    if some_dynamic_property:
        return static_file('some-file-A')
    else:
        return static_file('some-file-B')
```

Given that:
- The modification time of `some-file-A` (as provided by the filesystem) is greater than that of `some-file-B`.
- `some_dynamic_property` is `True`.

Then, the following situation can occur:
- A client fetches `/some-url`.
- A 200 response arrives with the contents of `some-file-A` and its `Last-Modified` header set to that file's modification date.
- `some_dynamic_property` is changed to `False` (meaning future requests should yield `some-file-B`).
- The same client requests `/some-url` again, with the `If-Modified-Since` header set to the previously received
  `Last-Modified` value.
- **A 304 Not Modified response is returned**, leading the client to continue using `some-file-A`.
### Expected behavior

Instead of a 304 response, a 200 response with the contents of `some-file-B` should have been returned.
### Cause

In order to determine whether to return a `304 Not Modified` response, `static_file` compares the `If-Modified-Since` header of the request to the modification date of the file to serve. However, it incorrectly assumes this modification date actually corresponds to the same file; when this is not the case (i.e. whenever one route may serve more than a single different file), it incorrectly tells the client it can reuse the previous result.
### Quick workaround

Unset the `Last-Modified` header:

```
@get('/some-url')
def someFile():
    if some_dynamic_property:
        resp = static_file('some-file-A')
    else:
        resp = static_file('some-file-B')

    resp.set_header('Last-Modified', '')
    return resp
```

Note that **this disables client-side caching for this URL**, which is often undesirable. Otherwise, one has to manually implement one of the solutions listed below.
### Potential solutions
- Stop using the `Last-Modified` header for caching but instead provide an `ETag`, derived from a checksum/hash of the file contents.
- A disadvantage of the previous approach is that the file always has to be read in its entirety before a hash can be calculated. This can be prevented by caching hashes until the corresponding files change, or by obtaining the tag by hashing a file's path along with its modification date.
- Add an argument to `static_file` that allows a caching method to be selected. The options could be `'none'`,
  `'etag'`, `'last-modified'` and `'etag+last-modified'`. Preferably `'last-modified'` should not be the default.
- Declare this to be intended behavior, but explicitly mention this issue in the documentation of `static_file`.

I hope that this problem can be resolved. If desired, I could provide a patch implementing one of these solutions myself.

**Comment by THEGOLDENPRO** [comment]
I have the same problem, why hasn't this been fixed after 7 years and why has the issue been ignored?

**Comment by THEGOLDENPRO** [comment]
Actually never mind, seems like it's working now after hard-refreshing my browser cache.

**Comment by defnull** [comment]
The method doc string specifies that `If-Modified-Since` is honored, and it should be obvious that the implementation uses the modification time of the actual file being served for comparison. So, `static_file()` behaves as documented.

If you want to prevent caching, set the appropriate response headers or remove the `If-Modified-Since` header before calling `static_file()`. Clearing your local cache obviously also helps, but that's only a local fix.

Master branch also already supports etag, so this issue can be closed I guess.

**Comment by THEGOLDENPRO** [comment]
> The method doc string specifies that `If-Modified-Since` is honored, and it should be obvious that the implementation uses the modification time of the actual file being served for comparison. So, `static_file()` behaves as documented.
> 
> If you want to prevent caching, set the appropriate response headers or remove the `If-Modified-Since` header before calling `static_file()`. Clearing your local cache obviously also helps, but that's only a local fix.
> 
> Master branch also already supports etag, so this issue can be closed I guess.

This helped, thank you. 💛
