### ISSUE TITLE
A False `secure` option on `set_cookie` marks cookie as secure in response headers

### ISSUE THREAD

**Issue by evrom** [bottlepy/bottle#735]
if i execute 
```
response.set_cookie('s', signed_session,
                            path='/', secure=False)
```
it will require HTTPS on the cookie. It should only do this when `secure=True`. If I remove the `secure` keyword, it does not mark it as secure (as it should).
Does anyone else have this problem? I am running this on python 3.4 on archlinux.

**Comment by defnull** [comment]
This is the default behavior of the stdlib cookie implementation:
https://hg.python.org/cpython/file/2.7/Lib/Cookie.py#l508

I added a quick check to get a more intuitive behavior.
