### ISSUE TITLE
bottle-boilerplate, structure (MVC) for anyone who wants to use bottle

### ISSUE THREAD

**Issue by avelino** [bottlepy/bottle#742]
**Is not a rule to follow, just that you would like to be able to use!**

For those who begin to use Bottle gets lost with the total freedom that the framework of, that's great for software architect. On the other hand we have problem with developers who don't want to take decision of software architecture, so I started the project bottle-boilerplate[1].

What do you think of migrating the repository into the organisation of the bottle? And be maintained as a project officer in the Bottle?

If so, it would be important to migrate the repository for the Organization of the bottle (do not create a blank repository).

[1] https://github.com/avelino/bottle-boilerplate

**Comment by avelino** [comment]
@defnull What do you think?

**Comment by foxbunny** [comment]
What's wrong with it being maintained as a 3rd party project?

**Comment by avelino** [comment]
@foxbunny no, but we can put inside the bottle, as well organization be an official package maintained by bottle and not just by Avelino maintained!

**Comment by foxbunny** [comment]
Personally I don't really care whether it's official or not. If it's a good tool, I use it.

**Comment by foxbunny** [comment]
If it is a good tool, though, a reference from the docs wouldn't hurt.

**Comment by wenzul** [comment]
Also interesting: https://github.com/salimane/bottle-mvc
