### ISSUE TITLE
Do you have the document for Bottle of early version?

### ISSUE THREAD

**Issue by ladder1984** [bottlepy/bottle#745]
Hi,
I am a novice programmer of Python Web from China.I want to develop a web framework of myself.Now,I want to learn from bottle.However,I find Bottle 0.12 a little complicated,and the Bottle 0.4.3 have only about 700 lines,so ,I want to learn from it know.Do you have the document for Bottle of early version?0.4 or any other early version?Please e-mail them to me.What'more,I can only read English document.

Thanks.

**Comment by foxbunny** [comment]
It looks like the first version that has anything to do with API docs is [0.7.1RC](https://github.com/bottlepy/bottle/tree/0.7.1rc). Before that it was extracting pages from the GH wiki, which I don't think would be useful now.

I'd suggest you work with the current version, though. I'm pretty sure tons of bugs have been fixed meanwhile, and important features introduced. It might be a lot to handle for a novice developer, but I'm sure the time you invest in it would be well worth it.

**Comment by defnull** [comment]
Everything ever written should be in git history. Even the wiki pages were copied there some time. 

For a more history view on things, there is a (german) forum thread here: http://www.python-forum.de/viewtopic.php?t=19451 This is literally the first hour of the bottle project ;)
