### ISSUE TITLE
prevent run() function pass argument parser object to gunicorn server

### ISSUE THREAD

**Issue by aacanakin** [bottlepy/bottle#756]
I have an argument parser that have an `--env, -e` option which is different from gunicorn's `--env, -e`. When I call run with the following parameters;

``` python
kwargs = { 'workers': 4 }
bottle.run(app.wsgi,
           host='localhost',
           port=8080,
           debug=False,
           reloader=False,
           server='gunicorn',
           **kwargs)
```

The `run()` function sends gunicorn to my previously created ArgumentParser object unexpectedly and gives the following error;

```
Error: environment setting 'production' invalid
```

This error is coming from gunicorn's config module;
https://github.com/benoitc/gunicorn/blob/master/gunicorn/config.py#L187
How can I solve this problem?
NOTE: I don't want to change --env option to some other thing

**Comment by defnull** [comment]
Why is gunicorn parsing command line args when it is instantiated programmically?

**Comment by aacanakin** [comment]
bottle probably run cli app of gunicorn when server option is set to gunicorn

**Comment by nerandell** [comment]
Any updates on this issue?

**Comment by defnull** [comment]
The original issue was closed without a solution back in 2010: https://github.com/benoitc/gunicorn/issues/91 Starting gunicorn from within another program was not supported officially. Seven years later, there might now be documented way to do this: http://docs.gunicorn.org/en/latest/custom.html

I have no idea if the commandline-args-pasring issue is solved on gunicorn side, though.
