### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by foxx** [bottlepy/bottle#759]
No problem here, just a little note to thank all the maintainers for their love and hard work that has gone into this project. It has saved me a lot of time, and I can only thank you for sharing this with us all.

**Comment by cgloeckner** [comment]
+1
Great project!

**Comment by Mirodin** [comment]
I join this, awesome project!

**Comment by defnull** [comment]
Thanks a lot but I still have to close this issue :)

**Comment by kurttheviking** [comment]
:+1:
