### ISSUE TITLE
Why we use a copy of `cls.settings` in bottle

### ISSUE THREAD

**Issue by andyxning** [bottlepy/bottle#762]
What is the purpose of `cls.settings = cls.settings.copy()` in [bottle.py](https://github.com/bottlepy/bottle/blob/master/bottle.py#L3367).

**Comment by foxx** [comment]
This prevents the original settings object from being modified, as documented in the class with `# Make settings local to class`. For example, if you use a settings object for multiple classes and one class modifies it, then that change would also be applied onto all other classes, which is likely to be undesired behaviour.

**Comment by andyxning** [comment]
i understand that. Thanks a lot.
