### ISSUE TITLE
Naming convention inconsistency

### ISSUE THREAD

**Issue by foxx** [bottlepy/bottle#763]
HTTP response codes are referenced as both `status` and `code` throughout the code, which gives the feeling of naming inconsistency. 

One particular example would be `HTTPError`, this class uses `code` where as it's immediate parent `HTTPResponse` uses `status` instead. Although this would result in a backwards incompatible change, it would be nice to see this naming cleaned up on the next major release.

Thoughts?

**Comment by eric-wieser** [comment]
[I don't see `.code` anywhere](https://github.com/bottlepy/bottle/blob/master/bottle.py#L1786-L1796)

**Comment by eric-wieser** [comment]
I think you're thinking of `.status_code` vs `.status_line` vs `.status`, which are [different views on the same data](https://github.com/bottlepy/bottle/blob/master/bottle.py#L1547-L1580)

**Comment by foxx** [comment]
This is really strange, I must have been looking at a modified fork, as I just checked the `master` branch and indeed the code/status mismatch is not there. Serves me right for not checking master first, my apologies, thanks.
