### ISSUE TITLE
DeprecationWarning: Switch to Plugin API v2

### ISSUE THREAD

**Issue by bootsmann** [bottlepy/bottle#770]
I am using bottle v0.12.8 with bottle-sqlite and whenever I start the server I get a warrning:

/usr/local/lib/python2.7/dist-packages/bottle.py:527: DeprecationWarning: Switch to Plugin API v2 and access the Route object directly.
context = self if api > 1 else self._context

**Comment by camconn** [comment]
You should set a class value for the `api` key. This is used by bottle to detect whether or not the older or newer API is being used.

For example
```python

class MyPlugin(object):
    '''Example Plugin '''

    name = 'MyPluginName'
    api = 2  # You need to set this

    def __init__(args):
    ...

```

**Comment by bootsmann** [comment]
Thx.
It is an bottle-sqlite problem. On pypi there is an old version.

**Comment by camconn** [comment]
This bug is now filed in bottlepy/bottle-sqlite#10.

I recommend closing this issue.
