### ISSUE TITLE
i should use request.url to distinguish whether the request comes from localhost. right?

### ISSUE THREAD

**Issue by saintthor** [bottlepy/bottle#771]
i will run the server for both local and remote user. i distinguish the request's source as below.

if request.url.find( 'http://localhost:' ) == 0:
   pass
else:
   pass

is it the best way?  thanks.

**Comment by eric-wieser** [comment]
That code finds if the request _goes to_ `localhost`, not comes from

**Comment by saintthor** [comment]
is there any difference?

isn't gose to same with comes from?

**Comment by defnull** [comment]
No, the host depends on a client-submitted `Host` header. Check `request['REMOTE_ADDR'] == '127.0.0.1'` to be sure. Nothe that this is always the local address if you use a reverse proxy or load balancer in front of your webserver.
