### ISSUE TITLE
FR: Dissection of Accept header

### ISSUE THREAD

**Issue by foxx** [bottlepy/bottle#790]
Currently the only way to inspect the Accept header is to manually apply string splitting, for example;

```py
found = []
lines = request.headers.getall('Accept', [])
for line in lines:
    found += line.split(",")
```

It would be nice if bottle had support for this out of the box, perhaps something like;

```
request.accept_content_type = ['application/json', 'text/html']
```

Admittedly the naming convention of `accept_content_type` is a bit crappy, so I'd welcome other suggestions.

Thoughts?

**Comment by foxx** [comment]
After tumbling down the rabbit hole, I've emerged with a complimentary library which handles content negotiation and media type rendering, with pretty much flawless results. I'm going to close this issue out for now, but will update it with a link once the library is stable.

**Comment by sharpaper** [comment]
What library?
