### ISSUE TITLE
We must save the file first as a static-file before download it in bottle?

### ISSUE THREAD

**Issue by shnode** [bottlepy/bottle#802]
i've notice the manual:

    @route('/download/<filename:path>')
    def download(filename):
        return static_file(filename, root='/path/to/static/files', download=filename)

what can i do to put it into the response's stream without save it.

**Comment by eric-wieser** [comment]
`static_file` is specifically for files that are saved in the file system, ie are static.

What are you trying to achieve?

**Comment by shnode** [comment]
`werkzeug` and its `ResponseStreamMixin` for Response meet the demand. Thanks.
