### ISSUE TITLE
Response's charset ignored when returning a dictionary (as json)

### ISSUE THREAD

**Issue by Bramas** [bottlepy/bottle#819]
Hello,
First of all thanks a lot for the great tool, it's the best and the simplest lib to create API with python.

I saw that when returning a dict, it is automatically converted to json and the content-type header is automatically set to `application/json`.
That's nice but in this case the charset is ignored. Usually, we want the content-type to be `application/json; charset=utf-8`
(the charset can be different for those who explicitly set another charset before returning the dict, but now there is no way to set the charset in the response when returning a dict.

I think this happens at line 1960 (in bottle.py master):
```python
    if isinstance(rv, dict):
        #Attempt to serialize, raises exception on failure
        json_response = dumps(rv)
        #Set content type only if serialization successful
        response.content_type = 'application/json'
        return json_response
``` 
Maybe we can have something like this instead:
```python
    response.content_type = 'application/json; charset=' + response.charset
```

what do you think?

**Comment by defnull** [comment]
See http://stackoverflow.com/questions/19814908/why-content-type-header-to-use-for-json-application-json-charset-utf-8-or
