### ISSUE TITLE
Unable to set charset property (as presented in the official tutorial)

### ISSUE THREAD

**Issue by Bramas** [bottlepy/bottle#820]
Hello (again)

The official tutorial explain that we can set the charset of the response like that 

``` python
response.charset = 'ISO-8859-15'
```

However in the code, charset is just a read only property. I don't know if it was also a writable property in the past but If you want I can make a PR either by removing this from the doc, or making this property writable. 
What do you think?

**Comment by defnull** [comment]
Closed as duplicate for #1048 (this one was first, the new issue has more info. Thanks anyway!)
