### ISSUE TITLE
Plugin execution order

### ISSUE THREAD

**Issue by foxx** [bottlepy/bottle#825]
It would appear that global plugins are not called in an expected order.

For example;

```python
bottle.install(DatabasePlugin())
bottle.install(PluginThatNeedsDatabase())
```

The above would first call `PluginThatNeedsDatabase()`and then `DatabasePlugin()`. 

This goes against the advice seen in [documentation][1];

> The order of installed plugins is significant, though. If a plugin requires a database connection, you need to install the database plugin first.

As you can see from our example though, the database plugin cannot be installed first, otherwise dependant plugins will not work correctly.

You can see a full demonstration of this in action [here][2].

I would argue that the execution order of app plugins and view plugins should be the same, but as you can see from this [line][3], this is not the case. There are also backwards compatibility concerns with such a fix, given that it will almost certainly break every app in existence with plugin dependancies.

Thoughts @defnull ?

[1]: http://bottle.readthedocs.org/en/latest/tutorial.html#application-wide-installation
[2]: http://blog.bilak.info/2015/07/05/bottle-plugin-lifecycle/
[3]: https://github.com/bottlepy/bottle/blob/master/bottle.py#L595

**Comment by foxx** [comment]
Another idea would be to add the concept of "plugin dependancies", which is then used to determine the preferred execution order of plugins. This would allow plugins to satisfy their dependancies, without breaking backwards compatibility.

For example;

```python
class Plugin1(object):
    name = 'plugin1'

class Plugin2(object):
    name = 'plugin2'

class Plugin3(object);
    name = 'plugin3'
    depends = ['plugin1', 'plugin2']

app.install(Plugin3())
app.install(Plugin1())
app.install(Plugin2())
```

Execution chain would be `Plugin1()`, `Plugin2()`, `Plugin3()`.

I still feel that the execution order should be consistent, however this might be one of those situations where a "bug" becomes a feature.

**Comment by foxx** [comment]
After much trial and error, it would seem that most simple option for now is to provide an optional flag that  changes the plugin execution order. The default option could keep current functionality, with a view towards changing the default on a later revision (assuming that this issue is accepted).

Something like;

```
app = Bottle(plugin_order_reversed=True)
```

Naturally it will need a better attribute name. Thoughts?

**Comment by foxx** [comment]
In the mean time, here's a small mixin that implements this functionality. Happy to throw together a proper PR if this is accepted;

```python
class RouteMixin(object):
    """Allow plugins to be executed with dependancy chain"""

    def all_plugins(self):
        plugins = list(super(RouteMixin, self).all_plugins())
        if not self.app.plugins_reversed:
            app_plugins = list(reversed([ p for p in plugins if p in self.app.plugins ]))
            view_plugins = [ p for p in plugins if p in self.plugins ]
            plugins = app_plugins + view_plugins
        return plugins


class RouterMixin(object):
    def match(self, *args, **kwargs):
        route, args = super(RouterMixin, self).match(*args, **kwargs)
        extend_instance(route, RouteMixin)
        return route, args


class BottleReversePluginMixin(object):
    def __init__(self, *args, **kwargs):
        super(BottleReversePluginMixin, self).__init__(*args, **kwargs)
        self.plugins_reversed = kwargs.pop('plugins_reversed', False)

class Bottle(BottleReversePluginMixin, bottle.Bottle):
    pass
```

**Comment by foxx** [comment]
Also there's another problem, application wide plugins are executed /after/ view specific plugins. Again this is surprising behaviour if you have a plugin on the view which relies on a plugin in the app.

**Comment by foxx** [comment]
After even more trial and error, I was able to resolve my original problem by refactoring my plugins. I'm going to close this out, but if anyone else feels it needs attention then feel free to re-open.

**Comment by defnull** [comment]
Plugin order *should* work like this: If you install two Plugins P1 and P2 to the application and two Plugins P3 and P4 to the route (in that order), the flow graph for each request looks like this:

    request  -> P1 -> P2 -> P3 -> P4 \
                                      handler()
    response <- P1 <- P2 <- P3 <- P4 /

Each plugin can do stuff before it calls into the next plugin (or the handler in case of P4) and after it gets control back from the next plugin. If P1 is a database plugin, it creates the database connection before it calls into P2 and closes it after P2 returns control.

So, if it does not work like this, it is indeed a bug. But it is tested here: https://github.com/bottlepy/bottle/blob/master/test/test_plugins.py#L88

**Comment by foxx** [comment]
Thanks for the clarification @defnull. I can confirm that this is indeed working, and after refactoring my plugins I was able to get around the problem. 

I'm wondering if it's worth putting your above comment into the plugin docs page, as that made it quite clear, thoughts?
