### ISSUE TITLE
waitress, pass all options

### ISSUE THREAD

**Issue by schlitzered** [bottlepy/bottle#826]
the current implementation of the waitress adapter only passes self.host and self.port as an argument to serve(). but waitress accepts some more options, like "threads" would it make sense to call serve like this?
```
serve(handler, host=self.host, port=self.port, **self.options)
```

**Comment by Inndy** [comment]
Server adapters are designed for `bottle.run`, and it needs a lot of modify to `_cli_parse`.

If you needs other options, do this:
``` python
app = bottle.default_app()  # or your bottle.Bottle() instance
waitress.serve(app, host='127.0.0.1', port='8080', threads=33)  # and your options
```

**Comment by schlitzered** [comment]
hey, i am not talking about _cli_parse stuff, i am talking about that options that are passed to bottle.run(), also passed to the waitress server adapter.

The class ServerAdapter passed all unkown kwargs argument into self.options. The WaitressServer class inherits from ServerAdapter.

So the only thing that needs to be added is "**self.options" to the serve call from the WaitressServer Adapter.

**Comment by schlitzered** [comment]
BTW: I just created a pull request that will just do this.
