### ISSUE TITLE
Bottle incorrectly sets Content-Length header when status is 204

### ISSUE THREAD

**Issue by gbenson-wikia** [bottlepy/bottle#829]
Per [RFC 7230 3.3.2 p31](https://tools.ietf.org/html/rfc7230#section-3.3.2):

> A server MUST NOT send a `Content-Length` header field in any response with a status code of `1xx (Informational)` or `204 (No Content)`.

Unfortunately, Bottle does send the `Content-Length` header.

Minimal code example:
```
@delete('/foo')
def delete_foo():
    response.status = 204
    return response
```

Curl:
`curl 'http://localhost:8080/foo' -X DELETE -vvv`

Response:
```
HTTP/1.1 204 No Content
Content-Length: 0
Date: Fri, 05 Feb 2016 23:22:43 GMT
Server: myserver
```

**Comment by frankfarmer** [comment]
This interacts especially poorly with varnish 4.x stable which currently strictly interprets rfc7230

https://www.varnish-cache.org/trac/ticket/1826#comment:3
