### ISSUE TITLE
Fail to retrieve Content-Length from the HTTP response header

### ISSUE THREAD

**Issue by arnikz** [bottlepy/bottle#839]
I'm using bottle v0.12.9. For my web app I need to retrieve the Content-Length value. I tried both
approaches:
i) response.get_header('Content-Length') -> returned None
ii) response.content_length -> returned empty string ''

Error msg for the latter:

File "/Library/Python/2.7/site-packages/bottle.py", line 1416, in **get**
    return self.reader(value) if self.reader else value
ValueError: invalid literal for int() with base 10: ''

Thanks.

**Comment by defnull** [comment]
The client-provided "Content-length" header is in **request**.content_length, not **response**.

**Comment by arnikz** [comment]
Thanks. I need to log HTTP requests to a file (in Common Log Format) rather to a console but can't access Content-Length in the response header. **reques**t.content_length returns **-1** instead of **983** (as shown below)

log to console (debug mode) gives
127.0.0.1 - - [02/Mar/2016 13:46:32] "GET / HTTP/1.1" 200 **983**

**Comment by defnull** [comment]
A ´´request.content_length´´ of -1 indicates that the client did not provide a "Content-Length" header.

**Comment by arnikz** [comment]
OK, I think, we talk about different things here.  A client application (e.g. curl) making a request to my bottle-based web app returns the following HTTP response (header):

HTTP/1.0 200 OK
Date: Wed, 02 Mar 2016 15:40:43 GMT
Server: WSGIServer/0.1 Python/2.7.10
Content-Length: **983**
Content-Type: text/turtle
Allow: GET

In the console I get the corresponding access log. 
127.0.0.1 - - [02/Mar/2016 13:46:32] "GET / HTTP/1.1" 200 **983**

I would like to fetch **this** number using the API but neither response.content_length nor request.content_length helps. So what do you suggest to use?

**Comment by defnull** [comment]
Ahh okay! Unfortunately, bottle computes the content-length of a response only if it is not provided by the application or any plugin or hook. This happens at a very late moment in the pipeline, even after the `after_response` hook. The only way to get this number without computing it yourself is at WSGI layer.

This might help: http://blog.philippklaus.de/2013/06/wsgi-request-logger-logging-http-requests-with-any-wsgi-web-application-like-flask-bottle-or-django/

**Comment by defnull** [comment]
You usually create a pull request on github by forking the repository, then creating a patch in a branch of your own fork. No need to create branches in this repository. You can even use the in-browser editor and github will do all that (fork, branch, edit, create pull request) for you.

**Comment by defnull** [comment]
That said, the change would not help @arnikz much because `response.content_length` would still not return a meaningful value for the same reason described above.
