### ISSUE TITLE
using generators, setting content-type prevent data being transferred immediately

### ISSUE THREAD

**Issue by yoch** [bottlepy/bottle#850]
From the sample code [here](http://bottlepy.org/docs/dev/async.html#greenlets-to-the-rescue), if we add Content-Type header all data is transferred after 8 seconds.

```
from gevent import monkey; monkey.patch_all()

from time import sleep
from bottle import route, run, response

@route('/stream')
def stream():
    response.set_header('Content-Type', 'text/plain')   # <- here the change
    yield 'START'
    sleep(3)
    yield 'MIDDLE'
    sleep(5)
    yield 'END'

run(host='0.0.0.0', port=8080, debug=True, server='gevent')
```

**Comment by defnull** [comment]
When observing the network traffic (e.g. with tcpdump) the content is 
sent exactly as intended, with or without the extra header.

Most clients optimize buffering based on the content type. I suspect 
that "text/plain" enables line-buffering (flush after newline) while the 
default (text/html) is time-buffered (flush after some ms) by the client 
you are using. This is why the added content type seems to trigger a 
bug, while it is actually the client software that does unintended 
buffering.

Try with curl with the -N (--no-buffer) switch or add some newlines to 
your example.


Am 08.05.2016 um 23:04 schrieb yoch:

**Comment by yoch** [comment]
You're right, as curl shows.

But with regular browser, adding newlines doesn't help at all (on both firefox and chrome), so my concern is with clients.

**Comment by defnull** [comment]
You should perhaps consider web-sockets or SSE (server sent events) for real-time stuff.
Web-Sockers: http://bottlepy.org/docs/dev/async.html#finally-websockets
SSE: https://gist.github.com/werediver/4358735

**Comment by yoch** [comment]
OK, thank tou !
