### ISSUE TITLE
What exactly is a SomeAsyncWorker

### ISSUE THREAD

**Issue by kmcheung12** [bottlepy/bottle#851]
Stumbled upon this [SO question](http://stackoverflow.com/questions/20824218/how-to-implement-someasyncworker-from-bottle-asynchronous-primer)

In the page [Primer to Asynchronous Applications - EVENT CALLBACKS](http://bottlepy.org/docs/dev/async.html?highlight=worker#event-callbacks), it says 

    In order to conform to the WSGI standard, all we have to do is to return a body iterable that we can write to asynchronously
    ...

```@route('/fetch')
def fetch():
    body = gevent.queue.Queue()
    worker = SomeAsyncWorker()
    worker.on_data(body.put)
    worker.on_finish(lambda: body.put(StopIteration))
    worker.start()
    return body
```

How does one create a `SomeAsyncWorker`? What exactly is this?

**Comment by eric-wieser** [comment]
It is an object of your choosing, with 3 methods:
* `on_data(f)` - set the function to call when the worker has data
* `on_finished(f)` - set the function to call when the worker is done 
* `start()` - start the worked in a background thread

**Comment by kmcheung12** [comment]
I was wondering if I've missed some abstract class that guarantees asynchronous behaviour. If `SomeAsyncWorker` is just a class with 3 mentioned methods, it could still block forever on `.start()`

**Comment by eric-wieser** [comment]
How about `threading.Thread`? That has a `start` method that runs asynchronously.

I think you're missing the point here though - this documentation is explaining how to interface your _already asynchronous operation_ with bottle, not how to make an asynchronous operation.

**Comment by kmcheung12** [comment]
this documentation is explaining how to interface your already asynchronous operation with bottle

Make sense. Thanks for the clarification.
