### ISSUE TITLE
Bottle behind Apache

### ISSUE THREAD

**Issue by ioclaudio** [bottlepy/bottle#863]
Hi all,
is there a guide to use Bottle behind Apache with the module wsgi_module ?
I've found something but I can't split the routes on multiple modules.
Is it possible?
Thank you

Claudio

**Comment by defnull** [comment]
http://bottlepy.org/docs/dev/deployment.html#apache-mod-wsgi

Could someone with Apache/mod_wsgi experience please verify that the documentation on this is still up to date?

**Comment by ioclaudio** [comment]
At the end I've created a file called **app.wsgi** :

```
import sys
path = '/var/www/vhosts/mylib/app'
if path not in sys.path:
	sys.path.insert(0, path)
path2 = '/var/www/vhosts/mylib/app/mybottle'
if path2 not in sys.path:
	sys.path.insert(0, path2)
from csibottle import appCSI
application = appCSI
```

And I've created  a file called /var/www/vhosts/mylib/app/mybottle.py with this code
```
...
from bottle import Bottle, request, response, static_file, template

VERSION = "0.1"
appCSI = Bottle()
......
#####   PUBLIC METHODS #####

@appCSI.get('/hello')
def hello():
   return _formatStringResponse(MSG_HELLO)
```

It seems to work in the right way and all the paths are defined in the file mybottle.py.
