### ISSUE TITLE
SimpleTemplate, object / string confusion

### ISSUE THREAD

**Issue by mohierf** [bottlepy/bottle#869]
In a simple template file I get an object variable (eg `element`) that has some attributes which are also objects (eg. `check_command`).

In my template:
```
%name = 'check_command'
%value = element[name]
{{name}} = '{{value}}',  - {{type(value)}}
```
gives me: 
``` 
check_command = '<command, id: 57a19eb806fd4b15409677c4, name: check_host_alive, status: unknown>', <class 'alignak_webui.objects.item_command.Command'>
```
which is what I expect: the name of my attribute, followed by its value and the type of the value. Note that the type of this value is a class because my attribute contains an object.

But when I want to get this value object attributes, I get an AttributeError exception because my object is now considered as a string ! When dumped, the value is an object, but when used it is a string ... did I missed something ?

```
{{type(value)}} - {{value.id}}
AttributeError: 'str' object has no attribute 'id'
```

```
{{type(value)}} - {{value['id']}}
TypeError: string indices must be integers, not str
```

```
{{type(value)}} - {{getattr(value, 'id')}}
AttributeError: 'str' object has no attribute 'id'
```

**Comment by defnull** [comment]
Cannot reproduce. The expression:
    {{type(value)}} - {{value.id}}
is compiled to (pseudocode):
    _buffer.extend((_htmlescape(type(value)), " - ", _htmlescape(value.id), "\n"))
and should work as expected. 

The test case for python expressions within curly-braces is here: https://github.com/bottlepy/bottle/blob/master/test/test_stpl.py#L45

**Comment by defnull** [comment]
Sorry, looks like there must be something wrong with your template or application code.

    >>> import bottle
    >>> from collections import namedtuple
    >>> value = namedtuple('ValueType', 'id')(5)
    >>> bottle.template('{{type(value)}} - {{value.id}}', value=value)
    u'&lt;class &#039;__main__.ValueType&#039;&gt; - 5'
    >>> bottle.template('{{!type(value)}} - {{value.id}}', value=value)
    u"<class '__main__.ValueType'> - 5"

**Comment by mohierf** [comment]
Thanks for your reply!

I found a temporary workaround:
```
         %linked_object = value
         %for method in dir(linked_object):
         %if callable(getattr(linked_object, method)) and method=='get_html_link':
         %get_link = getattr(linked_object, method)
         %end
         %end

         %for method in dir(linked_object):
         %if not callable(getattr(linked_object, method)) and method=='__dict__':
         %get_dict = getattr(linked_object, method)
         %end
         %end
```

This allows to get the callable `get_html_link` method in `get_link` and the object inner dictionary in `get_dict` ... then I can write: 
```
    {{get_dict['_id']}}
```

Else: {{linked_object['_id']}} raises an exception ...

I will try to find some time to have a look in your test module to build a test case that reproduces the problem ...
