### ISSUE TITLE
bottle 0.12.9 PyPI package: touni doesn't contain None to empty string fix

### ISSUE THREAD

**Issue by Larivact** [bottlepy/bottle#870]
When you install the newest bottle version with pip you get the following behavior:

```
>>> from bottle import template
>>> template('{{foo}}', foo=None)
'None'
```

In #562 from 2013 this got fixed so that it returns an empty string instead, and the fix is currently [in the master branch](https://github.com/bottlepy/bottle/blob/master/bottle.py#L199), however it somehow isn't in the bottle 0.12.9 PyPI package.

@defnull You could probably update that package to contain the fix, because this is quite inconvenient when setting the value of HTML inputs.

**Comment by eric-wieser** [comment]
> somehow isn't in the bottle 0.12.9 PyPI package

0.13 development began in daeb2dd20fa28de50bb1b921975251695c779754 (2013), which explains why it's not in 0.12.x.

Perhaps this is considered a breaking change, so was not put in 0.12.x. Or maybe the issue is that the PRer targeted master when they should have targeted the release branch

**Comment by Larivact** [comment]
@eric-wieser That's a logical explanation. I guess that I will have to monkey patch bottle as long as there is no new release that can return an empty string for None values.

```
import bottle
from bottle import template

def touni(s, enc='utf8', err='strict'):
    if isinstance(s, bytes):
        return s.decode(enc, err)
    else:
        return str(s or ("" if s is None else s))

bottle.touni = touni

print(template('{{foo}}', foo=None))
```
