### ISSUE TITLE
How to use static file easily?

### ISSUE THREAD

**Issue by magician333** [bottlepy/bottle#873]
I developed a blog with bottlepy,but I want to use a logo picture for every page,except use static_file function,have other methods to solve this problem?

**Comment by eric-wieser** [comment]
This sounds like it would work better on http://stackoverflow.com, as it does not appear to be a bug or a feature request

**Comment by magician333** [comment]
@eric-wieser I think bottle should add a more  convenient function for  problems like this

**Comment by eric-wieser** [comment]
I don't think you've given anyone enough information to understand your problem

**Comment by magician333** [comment]
@eric-wiesser well, I go to stackflow
