### ISSUE TITLE
catchall does not work with templates

### ISSUE THREAD

**Issue by sirex** [bottlepy/bottle#882]
Here is a simple test:

```python
def test_bottle():
    import bottle
    import webtest

    app = bottle.app()
    app.catchall = False

    @bottle.route('/hello/<name>')
    def hello(name):
        return bottle.template('hello_template', name=name)

    testapp = webtest.TestApp(app)
    testapp.get('/hello/world')
```

Here I expect to get full traceback, since `app.catchall` is `False`, but instead I get 500 error without possibility to see original traceback.

Related: https://github.com/bottlepy/bottle/issues/167

**Comment by defnull** [comment]
The problem is that TemplateError is a subclass of HTTPError and thus always caught and special-cased, even with ``catchall=false``. I don't see why TemplateError should be a HTTPError. Missing templates are applications errors after all. Perhaps we just change TemplateError then.
