### ISSUE TITLE
Permission to use Bottle's logo on DevDocs

### ISSUE THREAD

**Issue by Thibaut** [bottlepy/bottle#886]
Hi

https://github.com/Thibaut/devdocs/pull/459 adds Bottle's documentation to DevDocs (http://devdocs.io). Are you OK with the logo being part of DevDocs? 

Thanks

**Comment by defnull** [comment]
>  It is allowed to use the logo as a link to the bottle homepage or in direct context with the unmodified library. In all other cases please ask first.

I think the usage on DevDocs is covered by this statement in the README. So, yes, you may use the logo in this context. :+1:

**Comment by Thibaut** [comment]
Thanks 👍
