### ISSUE TITLE
FormsDict do not provide function as doc describe

### ISSUE THREAD

**Issue by Petelin** [bottlepy/bottle#901]
doc said 
`this container also supports attribute-like access to its values. `

ok, let say ask for `/hello?key=value`

you can get it by `request.params.key`, that is very pythonic then `request.params['key']`. i like it so much.

but did you the origin method you cannot replace it, such as `/hello?items=value`, you can not get items, you will find it is a function.

that make no sense, only confuse.any ideas?

**Comment by eric-wieser** [comment]
`FormsDict` is a subclass of `dict`. `dict` has the builtin method `.items()`, which returns a list of key-value pairs.

If the builtin methods of `dict` are to exist at all on FormsDict objects, then they __must not__ be replaced by a query string like `?items=value`, as you are suggesting, as this would cause code like the following to only work for some query strings:

    for name, value in requests.params.items():
        print(name, value)

So there are only two options here:
 
    * remove/rename all the builtin dict methods (perhaps by adding a leading underscore), but this breaks inheritance
    * leave everything as it is, and force people to be explicit about `params['items']` vs `params.items`. Rememberm "explicit is better than implicit".

I don't think it is reasonable to change anything here

**Comment by defnull** [comment]
> remove/rename all the builtin dict methods (perhaps by adding a leading underscore), but this breaks inheritance

Even this would not solve all issues, for example parameters that match python syntax keywords (`in`, `with`, `from`, ...)
