### ISSUE TITLE
No wheel for latest version 0.12.10

### ISSUE THREAD

**Issue by adamchainz** [bottlepy/bottle#902]
This project has `bdist_wheel` configuration in its `setup.cfg` but no wheel has been published. This implies that the `bdist_wheel` step was missed in release. A full sdist + bdist_wheel release can be done with `python setup.py clean sdist bdist_wheel upload`. You can also upload the wheel right now by checking out the source code at the version for the last release and running `python setup.py clean bdist_wheel upload`. This will speed up everyone's installs 🐇 😄

**Comment by defnull** [comment]
Done :)
