### ISSUE TITLE
Can not use global instance "response" to set_header, set_cookie and etc

### ISSUE THREAD

**Issue by machinewu** [bottlepy/bottle#910]
As following code, I use global instance "response" to set a HTTP header "test_header" and set a cookie.
But it does not work.
```python
from bottle import route, run, template, HTTPResponse, response, Bottle

@route('/hello/<name>')
def index(name):
	response.set_header('test_header', 'abc123')
	response.set_cookie('cccook', name, 'mysecret', path='/')
	resp = HTTPResponse('<b>Hello %s</b>!' % name)
	return resp

run(host='localhost', port=9999)
```

![pic1](https://cloud.githubusercontent.com/assets/4166753/20959771/b934ffc6-bc97-11e6-8530-1a38ac994d78.jpg)

Is the set_header and set_cookie method can not be used as above?
**I found some things in the code made me confused.**

---
In bottle.py, about `line 1891`, the defined of HTTPResponse:
```python
class HTTPResponse(Response, BottleException):
    def __init__(self, body='', status=None, headers=None, **more_headers):
        super(HTTPResponse, self).__init__(body, status, headers, **more_headers)

    def apply(self, other):
        other._status_code = self._status_code
        other._status_line = self._status_line
        other._headers = self._headers
        other._cookies = self._cookies
        other.body = self.body
```

In the "apply" method, why use the attributes(_status_code, _status_line, _headers, _cookies) of self are assigned to the other instance (other.xx <- self.xx)? Is it correct? Should not be turned over assignment (self.xx <- other.xx)?

I tried to modify the code of bottle.py to verify my idea, change the "apply" method to:
```python
    def apply(self, other):
        self._status_code = other._status_code
        self._status_line = other._status_line
        self._headers = other._headers
        self._cookies = other._cookies
        self.body = other.body
```
Get the result:
![2222](https://cloud.githubusercontent.com/assets/4166753/20960199/3be65bca-bc9a-11e6-93cd-e1aeeaf7ddb1.png)
The result is correct.

I'm not sure if the changes I make affect the entire framework code.
Please confirm, thanks.

**Comment by defnull** [comment]
`HTTPResponse` (and `HTTPError`) are exceptions and meant to override whatever some previous code defined in the global `response` object. They can be returned (as you did) but they still maintain their property that they _replace_ whatever is set in the global response.

In your example, you should either just return a string instead of a `HTTPResponse` and coninue working with the global `response` object, or instantiate `HTTPResponse` and use that instead of the global one.

    from bottle import route, run, template, HTTPResponse, response, Bottle
    
    @route('/hello1/<name>')
    def index1(name):
        response.set_header('test_header', 'abc123')
        response.set_cookie('cccook', name, 'mysecret', path='/')
        return '<b>Hello %s</b>!' % name

    @route('/hello2/<name>')
    def index2(name):
        resp = HTTPResponse('<b>Hello %s</b>!' % name)
        resp.set_header('test_header', 'abc123')
        resp.set_cookie('cccook', name, 'mysecret', path='/')
        return resp
    
    run(host='localhost', port=9999)

**Comment by machinewu** [comment]
Learn it! Thanks for you help! Response quickly!
