### ISSUE TITLE
Logical error in add_hook and __hook_reversed

### ISSUE THREAD

**Issue by pyx** [bottlepy/bottle#911]
As of [492985f4 in line 671](https://github.com/bottlepy/bottle/blob/492985f46318b2051bba6f427cdf4889397b10d5/bottle.py#L671):

```python
    __hook_reversed = 'after_request'
```
Hooks that are supposed to be called in reversed order should be in some sort of collection. It is set as a single string right now, which works as intended by pure accident, as in [line 688](https://github.com/bottlepy/bottle/blob/492985f46318b2051bba6f427cdf4889397b10d5/bottle.py#L688):
```python
        if name in self.__hook_reversed:
```
Here we are checking sub-string instead, it works because ```"after_request"``` is a sub-string of itself, but anything shorter will work, e.g:
```python
>>> 'after_request' in 'after_request'
True
>>> 'af' in 'after_request'
True
>>> 'a' in 'after_request'
True
```

**Comment by defnull** [comment]
Good catch! How did you find this one?

**Comment by pyx** [comment]
It's also by pure accident :).

I am about to write a gallery app/plugin and was reading the API reference, clicking the ```[source]``` link here and there, when I read ```add_hook``` and a few lines above, my instincts told me that something is not right...

I am going to read the whole source later on.
