### ISSUE TITLE
AttributeError: 'FileUpload' object has no attribute 'get_header'

### ISSUE THREAD

**Issue by jamiesonbecker** [bottlepy/bottle#918]
```
    content_type = upload.content_type
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1423, in __get__
    value = obj.get_header(self.name, self.default)
AttributeError: 'FileUpload' object has no attribute 'get_header'
```
From a different reporter:
http://stackoverflow.com/questions/21840723/devpi-attributeerror-fileupload-object-has-no-attribute-value-when-up

**Comment by defnull** [comment]
This affects 0.12.11 and I'm preparing a bugfix release --> bottle-0.12.12

Thanks for the report. This bug was not covered by our unit tests :(

**Comment by jamiesonbecker** [comment]
Thank you! Very fast!

**Comment by jamiesonbecker** [comment]
Works in my tests! Great, fast response, thank you!
