### ISSUE TITLE
'RuntimeError('maximum recursion depth exceeded in cmp',)' On post request

### ISSUE THREAD

**Issue by Mohamedemad4** [bottlepy/bottle#938]
whenever I try to send a POST request to /login it returns the following page
`Critical error while processing request: /login

Error:

RuntimeError('maximum recursion depth exceeded in cmp',)
Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 954, in wsgi
    out = self._cast(self._handle(environ))
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 908, in _cast
    return self._cast(out)
   .
   .
   .
   .

  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 906, in _cast
    out.apply(response)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1702, in apply
    response._status_code = self._status_code
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1664, in fset
    def fset(self, value): ls.var = value
RuntimeError: maximum recursion depth exceeded in cmp
`
as you see there were a lot of duplicate lines in that traceback, I tried: 
`@app.route('/login',method='POST')`
and then tried
`@app.post('/login')`
and when NONE worked 
i changed the recursion limit to 100000000
and that did not work
I am using bottle 0.12.13
, thanks in advance

**Comment by eric-wieser** [comment]
> i changed the recursion limit to 100000000

The problem is not that the recursion limit is too low, but that you're trapped in infinite recursion.

Which version of bottle are you using?

**Comment by defnull** [comment]
Your error handler returns an instance of `HTTPError`, which triggers the error handler, which returns an  `HTTPError` instance, which triggers the error handler, which ... reaches the recursion limit eventually and crashes.

Solution: Return `HTTPResponse` instead of `HTTPError`.

**Comment by defnull** [comment]
This is documented here, by the way: http://bottlepy.org/docs/dev/tutorial.html#error-pages
