### ISSUE TITLE
Config hook not raised when config is loaded from a file

### ISSUE THREAD

**Issue by mohierf** [bottlepy/bottle#941]
My aplication is loading its configuration from an `.ini` configuration file. I set an `@app.hook('config')` function and it is called when I change the configuration dictionary from within my application source code.

But, I noticed that when I change the content of the configuration file, the `hook` is not raised. Is it the expected Bottle behavior, I suppose so?

Any idea about the best solution to make the configuration get reloaded when the configuration file is updated; this will help to avoid Web server restarting 😉

**Comment by kianxineki** [comment]
I use a config in a .py file and so I can use the settings directly, and also the auto reload works when I develop

**Comment by mohierf** [comment]
Ok. I know this feature ... but my request is not only intended for development and I do not want to use the reload feature at all.

**Comment by defnull** [comment]
The hook is triggered whenever the config dict itself is modified, but it does not keep track of where the values came from originally. So, yes, thats expected behavior. At least until someone writes a plugin for that ;)

You can try this if you want to auto-reload config from a file:

    import threading, time, os
    def check_config(app, filename, interval=1):
        mtime = 0
        while True:
            if mtime < os.path.mtime(filename):
                mtime = os.path.mtime(filename)
                app.config.load_config(filename)
            time.sleep(interval)
    check_thread = threading.Thread(target=check_config, args=(app, "./config.ini", 1))
    check_thread.daemon = true
    check_thread.start()

(code untested)

**Comment by mohierf** [comment]
Thanks @defnull 
I will give a try with your suggested code and give some feedback

**Comment by mohierf** [comment]
If it may help someone that has the same need as I had, here is my functional source:
```
import threading, time, os
# -----
# Check application configuration file change
# -----
def check_config(app, filename, interval=5):
    print("Thread for checking configuration file change, file: %s" % filename)
    mtime = os.path.getmtime(filename)
    while True:
        time.sleep(interval)
        print("Checking configuration file change...")
        if mtime < os.path.getmtime(filename):
            print("Application configuration file changed, reloading configuration...")
            mtime = os.path.getmtime(filename)
            app.config.load_config(filename)
check_thread = threading.Thread(target=check_config, args=(app, app_configuration_file, 10))
check_thread.daemon = True
check_thread.start()

```
