### ISSUE TITLE
How to manually add parameter(s) to handler(s) at route point ?

### ISSUE THREAD

**Issue by iamybj** [bottlepy/bottle#953]
`
from bottle import static_file

def static_handler(path, root):
    return static_file(path, root=root)
`

`
app = Bottle()

app.get(path='/static/<path:path>', callback=static_handler, root='/webroot/static/')
`

`
TypeError: static_handler() missing 1 required positional argument: 'root'
`

**Comment by defnull** [comment]
With https://docs.python.org/3.6/library/functools.html#functools.partial or lambdas:

    app.get(path=..., callback=functools.partial(static_handler, root=...))
    app.get(path=..., callback=lambda **kw: static_handler(root=..., **kw)))

**Comment by iamybj** [comment]
too ugly code style.
bottle should add a feature that add route in code.
decoration route spread the @route all over the project, it is ugly.
