### ISSUE TITLE
make app.error can be used as a decorator or called directly

### ISSUE THREAD

**Issue by iamybj** [bottlepy/bottle#959]
""" Register an output handler for a HTTP error code.
        Can be used as a decorator or called directly ::
            
            def error_handler_500(error):
                return 'error_handler_500'

            app.error(code=500, callback=error_handler_500)

            @app.error(404)
            def error_handler_404(error):
                return 'error_handler_404'
    """

I have modified the code, but cannot pass The Travis CI build 

    def error(self, code=500, callback=None):
        """ Register an output handler for a HTTP error code.
            Can be used as a decorator or called directly ::
                
                def error_handler_500(error):
                    return 'error_handler_500'
                app.error(code=500, callback=error_handler_500)
                @app.error(404)
                def error_handler_404(error):
                    return 'error_handler_404'
        """
        
        def decorator(callback):
            if isinstance(callback, basestring): callback = load(callback)
            self.error_handler[int(code)] = callback
            return callback
        
        return decorator(callback) if callback else decorator

**Comment by defnull** [comment]
I merged your PR today :) Travis-CI builds were broken for a while (coverage failed) but should be working again.
