### ISSUE TITLE
Processing e-mail validation during account creation - using bottle framework

### ISSUE THREAD

**Issue by rkanamar** [bottlepy/bottle#960]
Team,
am using bottle framework for my web application. Respective to this work, we want to do email verification during registration process for creating a user account in our application. To proceed with this development, i didnt get any bottle related e-mail plugins and not able to close issue. Can you please let me know how to proceed with this issue.

**Comment by defnull** [comment]
Sending e-mails is not a bottle-specific task, why should there be a plugin for that?

https://docs.python.org/3.6/library/email-examples.html
