### ISSUE TITLE
is the django template engine supported?

### ISSUE THREAD

**Issue by AlJohri** [bottlepy/bottle#977]
Django templates have a standalone mode that can be used like below:

```python
from django.template import Context, Engine
engine = Engine()
template = engine.from_string("Hello {{ name }}!")
context = Context({'name': "world"})
text = template.render(context)
print(text)
```

I was wondering if it can be used with bottle?

Thanks!

**Comment by defnull** [comment]
Sure. You could look at one of the existing integrations (e.g. for Jinja2: https://github.com/bottlepy/bottle/blob/master/bottle.py#L3887 ) and publish it as an extension to bottle, or just use it directly to render strings and return them from your handler functions.

There really is not much to 'integrate'. Any template engine can be used with bottle, as long as it produces text or byte output that can be sent to the client.
