### ISSUE TITLE
Add SameSite support for cookies

### ISSUE THREAD

**Issue by hyde0620** [bottlepy/bottle#982]
It would be great if we can set "**SameSite**" flag via set_cookie function.

e.g. 
response.set_cookie(cookie_key, cookie_id, same-site-cookies='Lax', ....)

**Comment by provinzkraut** [comment]
For a workaround, you could just add it via `add_header()` like this:
`response.add_header('Set-Cookie', 'cookie_key=cookie_id; SameSite=Lax')`.

But indeed it would be nice to have this as a keyword for `set_cookie()`.

**Comment by provinzkraut** [comment]
However, if you want to do this via `set_cookie` you could modify your bottle.py like this:

import Morsel from http.cookies: `from http.cookies import Morsel`.
Then add the following to `set_cookie()`:
`Morsel._reserved['same-site'] = 'SameSite'`.

Now you can use the attribute `same_site` in `set.cookie()`, like
`response.set_cookie(cookie_key, cookie_id same_site="lax")`.

This updates the `_reserved` dict, which is used to check if an attribute is valid.

**Comment by hyde0620** [comment]
@provinzkraut  Thanks for the reply. 
It's a good way to add the attribute `same_site`. 👍

**Comment by oz123** [comment]
@defnull this issue is resolved.

**Comment by Teva** [comment]
Hi all,

Am I wondering if my issue is linked to this closed issue :

```python
 response.set_cookie(name = "name", value = name, secret='some-secret-key', httponly = True, same_site = 'strict')  #secure = True to be added in prod
```

this raises the following error with python 3.7 :
MYPATH--> /http/cookies.py", line 311, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'same-site'

**Comment by susundberg** [comment]
I ended up hitting the excatly the same error message with bottle 0.12.18 (Python 3.6.9)

**Comment by defnull** [comment]
The fix (or same-site support) was not back-ported to 0.12 yet.
