### ISSUE TITLE
A plugin isn't executed on every request; how to fix? 

### ISSUE THREAD

**Issue by elpres** [bottlepy/bottle#984]
The first time a route is accessed, everything works fine, but subsequent requests to the same route are missing headers that should be set by a plugin (and are set correctly on the first request). Am I doing something wrong? Here is the basic setup:

```python
class SessionExtender(object):
    name = 'session_extender'
    api = 2

    def apply(self, callback, route):
        # do some internal things ....
        bottle.response.set_cookie('session', session_id, path='/', expires=some_date())

        print('setting header')
        bottle.response.set_header('Cache-Control', 'no-cache, no-store, must-revalidate')

        return callback


app = bottle.Bottle()
app.install(SessionExtender())
app.run(host='0.0.0.0', port=8080, debug=True, reloader=True)
```

The plugin extends the current session on any new activity, but since our intranet is running a proxy, I need to disable caching of all content, otherwise problems with getting outdated content are reliably reproducible. That's why I'm also setting the `Cache-Control` header.

So here is what I see if I request a route twice with curl, first after a fresh server restart, and the second one immediately afterwards:

```
% curl -I -b "session=rzwDipsrxGYbKJHCnKxj" http://localhost:8080/en/modal/preview/542
HTTP/1.0 200 OK
Date: Fri, 14 Jul 2017 13:06:59 GMT
Server: WSGIServer/0.2 CPython/3.6.1
Cache-Control: no-cache, no-store, must-revalidate
Content-Length: 1388
Content-Type: text/html; charset=UTF-8
Set-Cookie: session=rzwDipsrxGYbKJHCnKxj; expires=Fri, 14 Jul 2017 21:06:59 GMT; Path=/


% curl -I -b "session=rzwDipsrxGYbKJHCnKxj" http://localhost:8080/en/modal/preview/542
HTTP/1.0 200 OK
Date: Fri, 14 Jul 2017 13:07:00 GMT
Server: WSGIServer/0.2 CPython/3.6.1
Content-Length: 1388
Content-Type: text/html; charset=UTF-8
```

Notice that both `Cache-Control` and `Set-Cookie` are missing the second time around.
And here is the access log from the server:

```
Bottle v0.12.13 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

setting header
/usr/lib/python3.6/re.py:301: DeprecationWarning: Flags not at the start of the expression ((?m)[urbURB]?(?:''( (truncated)
  p = sre_compile.compile(pattern, flags)
/usr/lib/python3.6/sre_parse.py:763: DeprecationWarning: Flags not at the start of the expression \{\{((?:((?m)[urbURB (truncated)
  p = _parse_sub(source, state, sub_verbose)
127.0.0.1 - - [14/Jul/2017 15:06:59] "HEAD /en/modal/preview/542 HTTP/1.1" 200 0
127.0.0.1 - - [14/Jul/2017 15:07:00] "HEAD /en/modal/preview/542 HTTP/1.1" 200 0
```

The second request doesn't print `setting header`, so I assume the plugin isn't executed the second time. Why does this happen and how can I make sure the `Cache-Control` header is set on every request?

**Comment by provinzkraut** [comment]
If you want something to be executed on every request, you should try using bottles `ad_hook()`.
It was specifically designed to do what you want: Execute something for each request and even comes with a handy decorator so you can use it like this:
```
@app.hook('before_request')
def do_my_stuff():
	# do stuff
	print("did stuff")
```

This would be called before processing on each request.
You can also use the `after_request` parameter, then it will be called after each request.
Look at [bottle API reference](http://bottlepy.org/docs/stable/api.html#bottle.Bottle.add_hook) for further information.

**Comment by defnull** [comment]
Yes, a hook would be easier. But more importantly, your plugin is broken. The `apply()` method is supposed to be a decorator and return a wrapped callable. Whatever it returns is called on every request. `apply()` itself is called only once, which is why it works for you on the first request, but not on subsequent requests. 

```
class SessionExtender(object):
    name = 'session_extender'
    api = 2

    def apply(self, callback, route):
        def wrapped(*a, **ka):
            bottle.response.set_cookie('session', session_id, path='/', expires=some_date())
            bottle.response.set_header('Cache-Control', 'no-cache, no-store, must-revalidate')
            return callback(*a, *ka)
        return wrapped
```

**Comment by elpres** [comment]
Ah, I see. I've been assuming that `apply()` is called every time. Thanks for the explanation, and also the library in general!
