### ISSUE TITLE
What route should I use when using bottle online

### ISSUE THREAD

**Issue by brains1960** [bottlepy/bottle#988]
Hello, I'm trying to use bottle as the web framework for my website I'm making with Netfirms. So basically I have uploaded the bottle.py file to my directory on netfirms and I'm importing it to files in the same directory and folder. Since this is an online directory I can't use the local host to run my site and therefore can't just set @route('/') for the home page. Does anyone know how I can go about figuring out what to put in the route() function?

**Comment by vascowhite** [comment]
Your ISP will have things set up so that '/' maps to www.yourdomain.tld/
So, `@route('/')` should work just fine.

**Comment by brains1960** [comment]
Does this work the same if the url is a link to a file? e.g. www.yourdomain.com/folder/file.py?

**Comment by defnull** [comment]
This bites a lot of people that come from PHP and try to use some other language: The PHP way (uploading scripts to a webspace and expecting the webserver to execute them) does not work. Cheap hosts like Netfirms list Python as their supported languages, but that is close to a marketing lie. They only support Python via CGI, which is barely usable. It's slow, cumbersome and not recommended for a lot of reasons. Netfirms documentation in this topic is useless, too.

Ditch Netfirms and choose a host that supports Python via WSGI. These usually have good documentation on how to get python applications running. Or get some cheap VPS if you are not afraid of linux server management and do it yourself.

It is important to understand the difference: With PHP, you have a webserver (e.g. apache) that executes PHP scripts. The request path (e.g. `/folder/file.php`) determines which script is executed. For each request, a new PHP runtime is created, the script is parsed and executed, and the runtime is destroyed again. All variables are lost in between requests. There is no shared state. This is why you need a database to do anything useful. 

With Bottle (or node.js, or ruby on rails, or any modern web framework) the webserver loads your entire application only once, and all requests, no matter the path, are handled to your application. The application then decides what to do with the request (e.g. bottle calls the matching route callback). This is why you can have nice paths (e.g. `/users/<id>`) that have nothing to do with files on the file system.

**Comment by brains1960** [comment]
Right I'll probably have to switch hosts or figure it out. Thank you
