### ISSUE TITLE
Support dict as input for add_header()

### ISSUE THREAD

**Issue by provinzkraut** [bottlepy/bottle#989]
Currently i'm adding multiple headers like this:
```
headers = {'some_header' : 'some_value', 'more_header' : 'more_value'}
for h, v in headers.items():
   add_header(h, v)
```

Wouldn't it be convenient  if `add_header()` supported multiple headers, as name/value pairs in a dict?
(and `set_header()` as well)

I think this could be easily done with something like:
```
if type(arg) == dict:
  for name, value in arg.items():
    self._headers.setdefault(_hkey(name), []).append(_hval(value))
else:
  self._headers.setdefault(_hkey(name), []).append(_hval(value))
```

Am missing something or isn't there a good reason that this coudn't be implemented?

**Comment by defnull** [comment]
What about `request.headers.update(header_dict)`?

**Comment by provinzkraut** [comment]
This is in fact a more elegant way of adding a dict to `response.headers`. Thanks for the hint!
I didn't think of this because i was too focussed on the iteration way i saw being used in `BaseResponse`.

However, i think this is just about convenience, right?
`add_header()` itself isn't _really_ nessecary as you can easily add a header via `response.headers['my_header'] = 'my_value'`, but it's nice to have. 
Or is there any common usecase where you really _need_ to do this with a function..?

**Comment by defnull** [comment]
Apart from convenience, `add_header` is a little bit faster for the usual use-case when you only need to add a header or two, because no `HeaderDict` wrapper is created. The code is inlined in this case. New users are also more likely to find `add_header` on the response object than diving into the `HeaderDict` API, and it's less typing.

So, yes, `response.add_header()` and friends are shortcuts for `response.headers.append()`. Use whatever is more convenient.

**Comment by provinzkraut** [comment]
Well.. It would be nice to have the possibility to add many headers without the overhead..
But on the other hand i think that there would be a decreased performance when adding single headers with the modified version of `add_header`. 

I let it run through timeit to see how big the differences are:

**Setting:**  20 headers, 1000000 repeats

1. Execution time for `response.headers.update()`: **30.032195936997596**
2. Execution time for looping over `header_dict` with `response.add_header()`: **30.203815396002028**
3. Execution time for looping over `header_dict` _within_ `response.add_header()`: **27.579744362999918**

Looping over `header_dict` with `response.add_header()`
```
for h, v in header_dict.items():
  response.add_header(h, v)
```

Looping over `header_dict` in`response.add_header()`
```
def add_header(self, *args):
  if type(args[0]) == dict:
    for h, v in args[0].items():
      self._headers.setdefault(_hkey(h), []).append(_hval(v))
  else:
    self._headers.setdefault(_hkey(args[0]), []).append(_hval(args[1]))
```

So 2nd performs a bit faster than 1st (as you said) but the real difference lies between 2nd and 3rd.

The performance drop when adding single headers:

Timeit at 1000000 repeats:
Performance of original `add_header`: **1.5151051540015033**
Performance of `add_header`, modified as in 3rd example: **1.6766795939984151**

At the end it comes down to noticeably better performance + convenience but in a not so common usecase **vs.** a bit worse performance in the common usecase.

I think common usecase wins.

**Comment by BubaVV** [comment]
It is possible to integrate type-check for the add_header(), but in this case we need to change function signature to add_header(*args, **kwargs), which is a bad idea, i think
