### ISSUE TITLE
pre-urldecode causes path parameters to become part of the route

### ISSUE THREAD

**Issue by ChaosData** [bottlepy/bottle#990]
Hi,

It appears that bottle pre-urldecodes the raw path string prior to passing it to the routing engine.
This has a couple of weird quirks and also probably violates the spirit of the HTTP spec relating to path handling (<https://tools.ietf.org/html/rfc3986#section-3.3>). In particular, this results in path segments consisting of path-like values being hoisted to the top level of the URL for routing purposes, and missing dynamic routes that should match. This prevents the path from being routed correctly, unless there is a `:path` wildcard filter applied. However, if this filter is applied, the `Request.fullpath` variable will not contain the correct string and will contain the post-decode "resolved" path.

For example, consider the URL: `http://127.0.0.1:8080/hello/foo%2fbar%2fbaz/world`

And the following code:
```python
from bottle import route, run, template, request

@route('/hello/<xmlxpath>/world')
def hello(xmlxpath):
    return template('<b>xmlxpath: {{xmlxpath}}<br>fullpath: {{fullpath}}</b>',
                    xmlxpath=xmlxpath, fullpath=request.fullpath)

run(host='localhost', port=8080)
```

The expected behavior is that the `hello` function will be called and that the following will render:

```
xmlxpath: foo/bar/baz
fullpath: /hello/foo%2fbar%2fbaz/world
```

The actual behavior is that the request 404s.

If we "fix" the code by adding a `:path` filter to the `<xmlxpath>` wildcard, as below, the same output is expected.

```python
from bottle import route, run, template, request

@route('/hello/<xmlxpath:path>/world')
def hello(xmlxpath):
    return template('<b>xmlxpath: {{xmlxpath}}<br>fullpath: {{fullpath}}</b>',
                    xmlxpath=xmlxpath, fullpath=request.fullpath)

run(host='localhost', port=8080)
```

However, the actual output is the following:

```
xmlxpath: foo/bar/baz
fullpath: /hello/foo/bar/baz/world
```

In the above, the fullpath contains a URL-decoded `<xmlpath>` segment value, which does not preserve the semantics of what was actually requested. However the issue goes deeper than this. Instead, consider the URL: `http://127.0.0.1:8080/hello/foo%2fbar%2f..%2f..%2fbaz/world`

The expected result of the page is the following:

```
xmlxpath: foo/bar/../../baz
fullpath: /hello/foo%2fbar%2f..%2f..%2fbaz/world
```

However, the actual result is the following:

```
xmlxpath: foo/bar/../../baz
fullpath: /hello/baz/world
```

In this case, not only is the path segment not preserved, it is pre-resolved in the fullpath.

Based on the RFC's definition of a path segment, both in structure and purpose, this behavior is troublesome as path segments are to be considered "considered opaque by the generic syntax." Furthermore, it goes on to state "URI producing applications often use the reserved characters allowed in a segment to delimit scheme-specific or dereference-handler-specific subcomponents."

While it would be tempting to say that ensuring the `Request.fullpath` value has the actual full path of the request would be enough to fix this, the pre-urldecoding behavior is already arguably "wrong" given the spec — most other web frameworks' (across languages) routing behaviors for this sort of route parameter syntax follow the spec as described — and `:path` behavior should be the default.

**Comment by provinzkraut** [comment]
This is an WSGI, or a general server issue.

If you try to access `request.environ['PATH_INFO']`, which holds an unaltered copy of the WSGI `environ['PATH_INFO']` you get the decoded path aswell.
WSGIref decodes the path before passing it into `environ['PATH_INFO']`.
In fact, the WSGI spec demands it (kind of like).

This is a known and well discussed decoding issue.
See [PEP 333 - Unicode issues](https://www.python.org/dev/peps/pep-0333/#unicode-issues) or
[Python bug tracker - Add advice about non-ASCII wsgiref PATH_INFO](https://bugs.python.org/issue16679) or
[django doesn't encode request.path correctly in python3](https://code.djangoproject.com/ticket/19468).

A workaround could be encoding  `%` aswell by replacing it with `%25`. `%2F` then would become `%252F`.

Or you could do something like:
```
from bottle import route, run, template, request
from urllib.parse import quote

@route('/hello/<xmlxpath:path>/world')
def hello(xmlxpath):
    return template('<b>xmlxpath: {{xmlxpath}}<br>fullpath: {{fullpath}}</b>',
                    xmlxpath=quote(xmlxpath, safe=""), fullpath=request.fullpath)

run(host='localhost', port=8080)
```

This will give you the desired result of:
```
xmlxpath: foo%2Fbar%2Fbaz
fullpath: /hello/foo/bar/baz/world
```

You could also do this in your own filter, that acts the same as `:path` but returns the matched part URL encoded.
(See [Bottle docs - Routing](https://bottlepy.org/docs/0.12/routing.html#wildcard-filters) for details)

**Comment by defnull** [comment]
Yes, @provinzkraut is correct. WSGI does not provide any way for bottle to access the raw path.

You are also correct, by the way. The RFC clearly states:

> URIs that differ in the replacement of a reserved character with its corresponding percent-encoded octet are not equivalent.  Percent-encoding a reserved character, or decoding a percent-encoded octet that corresponds to a reserved character, will change how the URI is interpreted by most applications.  Thus, characters in the reserved set are protected from normalization and are therefore safe to be used by scheme-specific and producer-specific algorithms for delimiting data subcomponents within a URI.

But unfortunately, WSGI (and some famous HTTP load-balancers and reverse proxies as well as most web frameworks) do not preserve encoded characters after the URI was successfully split into its components. `nginx` for example will also decode `%2F` in the path before passing the request to backend services by default.

I'd recommend not relying on percent-encoding too much. You will run into trouble all the time, not only with WSGI or Bottle, but with load-balancers and reverse-proxies as well.

(Closed because this cannot be solved in Bottle)
