### ISSUE TITLE
(v0.13-dev) Can't run aiohttp server

### ISSUE THREAD

**Issue by Michael-F-Ellis** [bottlepy/bottle#995]
```
Traceback (most recent call last):
  File "/Users/mellis/ls-mapped-mode/bottle.py", line 3709, in run
    server.run(app)
  File "/Users/mellis/ls-mapped-mode/bottle.py", line 3511, in run
    from aiohttp.wsgi import WSGIServerHttpProtocol
ImportError: No module named 'aiohttp.wsgi'
Bottle v0.13-dev server starting up (using AiohttpServer())...
```
Apparently aiohttp has obsoleted .wsgi. See https://github.com/aio-libs/aiohttp/issues/1108

Truth be told, my real interest here is to be able to run some background tasks as coroutines without having to resort to subprocesses or threads.  I read your writeup about using gevent but prefer to use asyncio and async/await since these are now built into Python.  Any suggestions?

Thanks!

**Comment by hartwork** [comment]
For the record you need `pip install aiohttp<2` to make that work.

Related commit:
https://github.com/aio-libs/aiohttp/commit/9218c264d57c633bc21cb7a14cd7890a272d4e34

**Comment by hartwork** [comment]
Related: #1118

**Comment by defnull** [comment]
Removing a non-working adapter (e.g. rocket) is fine. Removing a somewhat-working adapter that might be used by some users may be problematic without a deprecation round. On the other hand, it is very easy to just copy&paste the <10 lines from the old bottle release to your own application to re-introduce a removed adapter. If upstream dropped support already, it should be fine if we do so, too, without a deprecation-round.

**Comment by hartwork** [comment]
For `v0.13-dev` on `master` backend `aiohttp` uses `aiohttp-wsgi` as a bridge now supports `aiohttp>=2` (see 3d9a8c1d862a5fbbeb2676c283f5c42917702aa5). I believe this bug is fixed and can be closed.

**Comment by defnull** [comment]
Rocket was dropped in master and retrospectively deprecated in 0.12, so we can close this I think. Thanks :)

**Comment by hartwork** [comment]
Was that^^ comment was meant to go into #1119?
